import type { KnowledgeEntry } from "./types";

/**
 * Disease notes are written in plain English from the guidance published by
 * public plant-health bodies (see SOURCES in ./sources.ts). Nothing here is
 * copied text, and nothing is a prescription: always confirm the local label
 * of any product before you spray.
 */
export const DISEASES: KnowledgeEntry[] = [
  {
    slug: "early-blight",
    name: "Early Blight",
    scientificName: "Alternaria solani / Alternaria linariae",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "A common fungus of tomato and potato that starts on the oldest leaves and works its way up the plant as brown rings.",
    identification: [
      "Brown spots with rings inside them, like a tiny archery target.",
      "A yellow halo often surrounds each spot.",
      "The lowest, oldest leaves are hit first.",
      "Spots may join together until the whole leaf dries and hangs on the stem.",
    ],
    symptoms: [
      "Dark brown to black spots 3-12 mm wide with visible rings",
      "Yellowing of the leaf around and between spots",
      "Older leaves drop, exposing fruit to sunscald",
      "Dark sunken collar rot at the stem base of young transplants",
      "Leathery dark patches at the stem end of tomato fruit",
    ],
    causes: [
      "The fungus survives winter on crop debris, volunteer plants and in soil",
      "Rain and overhead watering splash spores onto lower leaves",
      "Long periods of leaf wetness let spores germinate",
      "Plants short of nitrogen or carrying a heavy fruit load give in faster",
    ],
    weather: ["Warm and humid", "Heavy rain", "Dew and fog"],
    weatherNote:
      "Most active at 24-29°C when leaves stay wet for a few hours, especially with alternating wet and dry days.",
    plants: ["Tomato", "Potato", "Eggplant", "Pepper"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Spring", "Summer", "Monsoon"],
    prevention: [
      "Rotate away from tomato-family crops for two to three years",
      "Use certified clean seed and healthy transplants",
      "Mulch the soil so rain cannot splash spores upward",
      "Space plants and stake them so leaves dry quickly",
      "Water at the base in the morning, never over the leaves",
    ],
    organic: [
      "Pick off and destroy the first spotted leaves before the spots spread",
      "Copper or sulphur products approved for organic growing, used early and repeated after rain",
      "Bacillus subtilis biofungicide sprays as a protective cover",
      "Keep plants fed and mulched so they can outgrow the lowest damage",
    ],
    chemical: [
      "Protectant fungicides such as chlorothalonil or mancozeb are the usual first choice in commercial fields",
      "Systemic groups such as azoxystrobin or difenoconazole are used when pressure is high",
      "Alternate between different chemical groups to avoid resistance",
      "Follow the label rate, spray interval and pre-harvest interval for your country",
    ],
    practices: [
      "Remove and destroy crop debris after harvest instead of ploughing it shallow",
      "Keep a two to three year gap before the same field grows tomato or potato again",
      "Scout the bottom leaves weekly from first fruit set",
      "Feed a balanced fertiliser; hungry plants lose leaves faster",
    ],
    tags: ["target spot", "concentric rings", "bottom leaves", "tomato", "potato", "alternaria"],
    related: ["late-blight", "septoria-leaf-spot", "alternaria-leaf-spot", "leaf-spot"],
    reviewed: "2026-07-15",
    added: "2026-07-15",
    popularity: 96,
  },
  {
    slug: "late-blight",
    name: "Late Blight",
    scientificName: "Phytophthora infestans",
    category: "disease",
    kind: "Oomycete",
    image: "blight",
    summary:
      "The fastest and most destructive disease of potato and tomato. In cool wet weather it can destroy a field in under two weeks.",
    identification: [
      "Pale green, water-soaked patches that turn brown or almost black.",
      "Damage often starts at leaf tips and edges.",
      "A soft white fuzz appears on the underside on damp mornings.",
      "There is no clear yellow ring around the lesion, unlike early blight.",
    ],
    symptoms: [
      "Greasy dark patches spreading quickly across leaves",
      "Brown to black streaks running up the stems",
      "White downy growth under the leaf in humid conditions",
      "Firm brown rot on tubers and fruit that later turns slimy",
      "A distinct sour smell from rotting tubers in store",
    ],
    causes: [
      "Spores blow in on wind and rain from nearby infected crops",
      "Infected seed tubers, cull piles and volunteer potatoes carry it over",
      "Cool nights plus long leaf wetness allow rapid new spore cycles",
      "Dense canopies that never dry out",
    ],
    weather: ["Cool and wet", "Heavy rain", "Dew and fog"],
    weatherNote:
      "Classic conditions are 10-20°C with humidity above 90% and leaves wet for 10 hours or more; a warning is issued when two such days follow each other.",
    plants: ["Potato", "Tomato", "Eggplant"],
    severity: "Very High",
    difficulty: "Hard",
    seasons: ["Spring", "Autumn", "Monsoon", "Winter"],
    prevention: [
      "Plant certified disease-free seed potatoes",
      "Choose resistant varieties where they are available locally",
      "Destroy cull piles and volunteer potatoes before the season starts",
      "Hill potatoes well so spores cannot wash down to the tubers",
      "Follow the national blight warning service if one exists in your area",
    ],
    organic: [
      "Remove and bury or burn infected plants at the very first sign",
      "Copper-based sprays applied before infection, repeated after each rain",
      "Wide spacing and open canopies so leaves dry fast",
      "Harvest two weeks after killing the haulm so tuber skins set",
    ],
    chemical: [
      "Protectants such as mancozeb before the disease arrives",
      "Targeted oomycete products such as cymoxanil, mandipropamid or fluazinam once risk is high",
      "Shorten the spray interval in wet weather and rotate chemical groups",
      "Always follow the local label and pre-harvest interval",
    ],
    practices: [
      "Scout daily during cool wet spells, not weekly",
      "Never store visibly rotten tubers with a healthy crop",
      "Kill the foliage before harvest in a bad blight year",
      "Report outbreaks to local extension staff so neighbours can react",
    ],
    tags: ["irish famine", "water soaked", "white mould underside", "potato rot", "phytophthora"],
    related: ["early-blight", "downy-mildew", "bacterial-wilt", "root-rot"],
    reviewed: "2026-07-15",
    added: "2026-07-15",
    popularity: 99,
  },
  {
    slug: "powdery-mildew",
    name: "Powdery Mildew",
    scientificName: "Erysiphe, Podosphaera and related genera",
    category: "disease",
    kind: "Fungal",
    image: "mildew",
    summary:
      "White dusty patches on the upper leaf surface. Unusual among leaf diseases because it thrives without rain.",
    identification: [
      "White to grey powder that can be rubbed off with a finger.",
      "Starts as small round patches, then joins into a felt-like coating.",
      "Mostly on the upper leaf surface and young shoots.",
      "Leaves under the coating turn yellow, then brown and papery.",
    ],
    symptoms: [
      "Circular white powdery colonies on leaves, stems and flower buds",
      "Yellow blotches showing through on the other side of the leaf",
      "Twisted or stunted young growth",
      "Early leaf fall and small, poorly flavoured fruit",
      "Reduced yield through loss of green leaf area",
    ],
    causes: [
      "Spores blow in on wind and need no free water to germinate",
      "High humidity at night with dry, warm days",
      "Shade, crowding and still air",
      "Soft, lush growth from too much nitrogen",
    ],
    weather: ["Mild and dry", "Poor airflow", "Dew and fog"],
    weatherNote:
      "Favoured by 20-27°C days, cool humid nights and dry leaves; heavy rain actually washes spores away.",
    plants: ["Cucumber", "Pumpkin", "Grape", "Wheat", "Rose", "Mango", "Pea", "Okra"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Spring", "Summer", "Autumn"],
    prevention: [
      "Grow resistant varieties, which exist for most cucurbits and grapes",
      "Give plants full sun and wide spacing",
      "Prune and train vines so air moves through the canopy",
      "Avoid heavy nitrogen pushes that create soft leaves",
    ],
    organic: [
      "Remove the first affected leaves and destroy them",
      "Sulphur dust or wettable sulphur, avoiding hot days above 30°C",
      "Potassium bicarbonate sprays, which work on contact",
      "Horticultural or neem oil, never mixed within two weeks of sulphur",
      "Milk-and-water sprays give partial control on light infections",
    ],
    chemical: [
      "Systemic groups such as myclobutanil, tebuconazole or difenoconazole",
      "Strobilurins are effective but resistance builds quickly if used alone",
      "Rotate chemical groups and stop before the pre-harvest interval",
    ],
    practices: [
      "Check the youngest leaves weekly in dry warm spells",
      "Treat at first sign; established mildew is much harder to clear",
      "Clear infected vine debris at the end of the season",
    ],
    tags: ["white powder", "dusty leaves", "cucurbit", "grape", "erysiphe"],
    related: ["downy-mildew", "rust", "leaf-spot", "scab"],
    reviewed: "2026-07-18",
    added: "2026-07-16",
    popularity: 92,
  },
  {
    slug: "downy-mildew",
    name: "Downy Mildew",
    scientificName: "Peronospora, Pseudoperonospora and Plasmopara species",
    category: "disease",
    kind: "Oomycete",
    image: "mildew",
    summary:
      "Yellow angular blotches on top of the leaf with grey or purple fuzz underneath. A wet-weather disease that spreads fast.",
    identification: [
      "Yellow patches on the upper side, squared off by the leaf veins.",
      "Grey, violet or almost black fuzz on the matching underside.",
      "Patches turn brown and brittle within days.",
      "Unlike powdery mildew, the growth is under the leaf and cannot be rubbed off easily.",
    ],
    symptoms: [
      "Angular yellow to brown blotches bounded by veins",
      "Downy grey-purple growth on the leaf underside in the morning",
      "Rapid browning and curling of whole leaves",
      "Bare vines with fruit left unprotected from the sun",
      "In grapes, oily spots on leaves and greying of young berries",
    ],
    causes: [
      "Wind-blown spores from warmer regions or nearby infected crops",
      "Free water on the leaf for several hours",
      "Dense canopies and overhead irrigation",
      "Cool nights with heavy dew",
    ],
    weather: ["Cool and wet", "Heavy rain", "Dew and fog", "Poor airflow"],
    weatherNote:
      "Needs leaf wetness; most aggressive at 15-23°C with humidity above 85%, and it stops in hot dry weather.",
    plants: ["Cucumber", "Grape", "Onion", "Spinach", "Lettuce", "Mustard", "Basil"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Spring", "Monsoon", "Autumn", "Winter"],
    prevention: [
      "Use resistant varieties where breeders offer them",
      "Irrigate at the base early in the day",
      "Open the canopy by pruning, trellising and correct spacing",
      "Do not work in the crop while foliage is wet",
    ],
    organic: [
      "Strip and destroy the first infected leaves",
      "Copper sprays applied protectively and renewed after rain",
      "Improve drainage and airflow before reaching for any spray",
    ],
    chemical: [
      "Oomycete-specific products such as mandipropamid, dimethomorph or metalaxyl in mixtures",
      "Keep protectant cover on new growth during wet spells",
      "Rotate groups; downy mildews develop resistance quickly",
    ],
    practices: [
      "Track regional forecast alerts during the rainy season",
      "Destroy crop residue rather than leaving it in the field",
      "Avoid planting the same family in the same bed each year",
    ],
    tags: ["angular yellow spots", "purple fuzz", "underside mould", "cucumber", "grape"],
    related: ["powdery-mildew", "late-blight", "leaf-spot", "rust"],
    reviewed: "2026-07-18",
    added: "2026-07-16",
    popularity: 88,
  },
  {
    slug: "leaf-spot",
    name: "Leaf Spot (general)",
    scientificName: "Many fungi and bacteria, various genera",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "A catch-all name for round dead spots on leaves. Telling the exact cause apart matters because treatment differs.",
    identification: [
      "Round or oval dead areas, tan, brown, grey or black.",
      "Fungal spots often have a defined edge and sometimes tiny dark dots inside.",
      "Bacterial spots look wet or greasy and are usually angular.",
      "Old spots can drop out, leaving a shot-hole look.",
    ],
    symptoms: [
      "Scattered spots that grow and join together",
      "Yellowing between spots followed by leaf drop",
      "Weak plants with less fruit because green leaf area is lost",
      "Spots concentrated on lower leaves in splash-spread diseases",
    ],
    causes: [
      "Splashing rain and irrigation moving spores or bacteria",
      "Infected residue and seed left from the previous crop",
      "Crowded plantings that stay wet",
      "Working among wet plants and moving the pathogen by hand",
    ],
    weather: ["Warm and humid", "Heavy rain", "Poor airflow"],
    weatherNote:
      "Most leaf spots need several hours of leaf wetness at 20-30°C to start a new infection.",
    plants: ["Tomato", "Banana", "Beet", "Chilli", "Ornamentals", "Beans"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Spring", "Summer", "Monsoon"],
    prevention: [
      "Buy clean seed and healthy seedlings",
      "Mulch to block soil splash",
      "Water at the base and space plants correctly",
      "Clean tools and hands between plants when scouting",
    ],
    organic: [
      "Remove and destroy the worst-hit leaves early",
      "Copper sprays for bacterial spots, sulphur or biofungicides for fungal ones",
      "Compost only if your heap reaches high temperatures; otherwise burn or bin",
    ],
    chemical: [
      "Broad protectants such as chlorothalonil or mancozeb for fungal spots",
      "Copper plus mancozeb combinations are common for bacterial spots",
      "Identify the cause first: fungicides do nothing against bacteria",
    ],
    practices: [
      "Photograph and log new spots so you can see if they spread",
      "Rotate crops and clear residue every season",
      "Do not save seed from a spotted crop",
    ],
    tags: ["spots", "shot hole", "brown spots", "general", "diagnosis"],
    related: [
      "septoria-leaf-spot",
      "cercospora-leaf-spot",
      "bacterial-leaf-spot",
      "alternaria-leaf-spot",
    ],
    reviewed: "2026-07-20",
    added: "2026-07-17",
    popularity: 78,
  },
  {
    slug: "anthracnose",
    name: "Anthracnose",
    scientificName: "Colletotrichum species",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Sunken dark lesions on fruit, leaves and stems, often with pink spore masses. A major cause of loss after harvest in mangoes and chillies.",
    identification: [
      "Sunken circular lesions with a dark edge.",
      "Salmon-pink or orange sticky spore masses in the centre when humid.",
      "On leaves, brown patches often follow the veins.",
      "Fruit rot may only appear after picking, as the fruit ripens.",
    ],
    symptoms: [
      "Dark sunken spots on ripening fruit that expand and soften",
      "Blackened flower clusters and dieback of young shoots",
      "Irregular brown leaf blotches",
      "Whole fruit collapse during transport and storage",
    ],
    causes: [
      "Spores survive on old fruit, twigs and leaf litter",
      "Rain splash and overhead irrigation move the sticky spores",
      "Fruit wounds from insects or handling give an entry point",
      "The fungus can stay silent inside green fruit and appear at ripening",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote:
      "Wet weather at 25-30°C during flowering and fruit development is the highest-risk window.",
    plants: ["Mango", "Chilli", "Banana", "Beans", "Papaya", "Avocado", "Grape"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Prune orchards for light and airflow, and remove mummified fruit",
      "Harvest at the right stage and handle fruit gently to avoid wounds",
      "Cool fruit quickly after harvest",
      "Use clean, treated seed for beans and chilli",
    ],
    organic: [
      "Collect and destroy fallen fruit and infected twigs",
      "Copper sprays during flowering and early fruit set",
      "Hot-water treatment of mango fruit after harvest, where facilities allow",
    ],
    chemical: [
      "Protective sprays from flowering: mancozeb, copper or azoxystrobin programmes",
      "Post-harvest dips are used commercially under strict local rules",
      "Rotate chemical groups and respect the pre-harvest interval",
    ],
    practices: [
      "Keep the orchard floor clean of fallen fruit",
      "Store fruit cool and dry, and never mix bruised fruit with sound fruit",
      "Track which blocks fail in storage so you can spray those first next year",
    ],
    tags: ["sunken spots", "fruit rot", "pink spores", "mango", "chilli", "colletotrichum"],
    related: ["black-rot", "scab", "leaf-spot", "canker"],
    reviewed: "2026-07-20",
    added: "2026-07-17",
    popularity: 74,
  },
  {
    slug: "rust",
    name: "Rust",
    scientificName: "Puccinia, Uromyces, Phakopsora and related genera",
    category: "disease",
    kind: "Fungal",
    image: "rust",
    summary:
      "Orange, brown or reddish powdery pustules that break through the leaf surface. In cereals it is one of the biggest yield threats worldwide.",
    identification: [
      "Raised pustules that burst and release rusty coloured powder.",
      "The powder stains a finger or cloth.",
      "Usually on the underside of broadleaf crops and both sides of cereal leaves.",
      "Colour may change to black late in the season.",
    ],
    symptoms: [
      "Rows or scattered orange-brown pustules on leaves and stems",
      "Yellowing and early death of leaves",
      "Shrivelled grain and lower test weight in cereals",
      "Whole crop bronzing in a severe outbreak",
    ],
    causes: [
      "Spores travel long distances on wind, sometimes between countries",
      "Dew or light rain gives the spores the moisture they need",
      "Susceptible varieties grown over a wide area",
      "Volunteer plants and alternate hosts carrying the fungus between seasons",
    ],
    weather: ["Dew and fog", "Warm and humid", "Mild and dry"],
    weatherNote:
      "Most rusts need several hours of dew at 15-25°C; hot dry afternoons alone will not stop them.",
    plants: ["Wheat", "Coffee", "Beans", "Soybean", "Maize", "Onion", "Rose"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Spring", "Winter", "Monsoon"],
    prevention: [
      "Plant resistant varieties, and change them as new rust races appear",
      "Sow early where local advice supports it, to escape peak spore load",
      "Remove volunteer cereals and nearby alternate hosts",
      "Avoid excessive nitrogen, which makes lush, susceptible growth",
    ],
    organic: [
      "Remove and destroy the first pustuled leaves in small plots",
      "Sulphur sprays give partial protection on garden crops",
      "Keep leaves as dry as possible with base watering and wide spacing",
    ],
    chemical: [
      "Triazoles such as tebuconazole or propiconazole are standard in cereals",
      "Strobilurin plus triazole mixtures give longer protection",
      "Spray at the first pustules; curative activity is limited once rust is established",
    ],
    practices: [
      "Scout the flag leaf in cereals; that leaf drives most of the yield",
      "Follow national rust surveillance bulletins",
      "Keep a variety mix across fields rather than one variety everywhere",
    ],
    tags: ["orange pustules", "wheat", "coffee leaf rust", "puccinia", "cereal"],
    related: ["powdery-mildew", "leaf-spot", "septoria-leaf-spot", "downy-mildew"],
    reviewed: "2026-07-21",
    added: "2026-07-18",
    popularity: 85,
  },
  {
    slug: "mosaic-virus",
    name: "Mosaic Virus",
    scientificName: "Tobacco mosaic virus, Cucumber mosaic virus and relatives",
    category: "disease",
    kind: "Viral",
    image: "virus",
    summary:
      "A patchwork of light and dark green on the leaf, with distorted growth. There is no cure once a plant is infected.",
    identification: [
      "Mottled light green, dark green and yellow patches with no clear edges.",
      "Leaves puckered, narrow, or curled like a fern.",
      "Whole plant stunted while the leaves stay attached.",
      "No fuzz, powder or wet lesion — that rules out most fungal causes.",
    ],
    symptoms: [
      "Mosaic mottling on young leaves first",
      "Blistered or crinkled leaf surface",
      "Stunted plants with poor, oddly shaped fruit",
      "Yellow streaks on stems in some crops",
      "Uneven ripening and reduced yield",
    ],
    causes: [
      "Aphids and other sap-sucking insects carry the virus between plants",
      "Contaminated hands, tools, clothing and tobacco products spread it by touch",
      "Infected seed, cuttings or transplants bring it into a new field",
      "Weeds around the field act as a hidden reservoir",
    ],
    weather: ["Warm and humid", "Hot and dry"],
    weatherNote:
      "The virus does not care much about weather, but warm conditions that boost aphid and whitefly numbers raise spread sharply.",
    plants: ["Tomato", "Cucumber", "Pepper", "Tobacco", "Squash", "Papaya", "Beans"],
    severity: "Very High",
    difficulty: "Hard",
    seasons: ["All year"],
    prevention: [
      "Buy certified virus-free seed and seedlings",
      "Grow resistant varieties where they are available",
      "Control aphids and whiteflies early, before they build up",
      "Wash hands and disinfect tools between plants, especially after tobacco use",
      "Keep the field edges free of host weeds",
    ],
    organic: [
      "Pull out and destroy infected plants as soon as you find them",
      "Reflective mulch to confuse incoming aphids",
      "Insect netting on nursery beds and young plants",
      "Encourage ladybirds and other natural aphid predators",
    ],
    chemical: [
      "No chemical cures a plant virus",
      "Insecticides are used only to reduce the insects that carry it, and can even increase spread if they scatter aphids",
      "Focus the budget on clean planting material and resistant varieties instead",
    ],
    practices: [
      "Handle healthy plants first and suspect plants last",
      "Do not save seed from infected plants",
      "Keep a two-week gap and clean the greenhouse between crops",
    ],
    tags: ["mottling", "mosaic", "crinkled leaves", "virus", "aphid spread", "no cure"],
    related: ["aphids", "whiteflies", "bacterial-wilt", "thrips"],
    reviewed: "2026-07-21",
    added: "2026-07-18",
    popularity: 81,
  },
  {
    slug: "bacterial-wilt",
    name: "Bacterial Wilt",
    scientificName: "Ralstonia solanacearum",
    category: "disease",
    kind: "Bacterial",
    image: "bacterial",
    summary:
      "A soil bacterium that blocks the water pipes inside the stem. Plants wilt in full green health and die within days.",
    identification: [
      "Sudden wilting while the leaves are still green.",
      "Cut stems show a brown ring and ooze a milky slime.",
      "A cut stem held in clear water releases white threads within minutes.",
      "Wilting starts in the hottest part of the day and does not recover at night.",
    ],
    symptoms: [
      "One-sided wilting that spreads to the whole plant",
      "Brown discolouration of the vascular ring in the stem",
      "Sticky white bacterial ooze from cut tissue",
      "Rapid plant collapse with no leaf spots",
      "Patches of dead plants that grow along the water flow of the field",
    ],
    causes: [
      "Bacteria live in soil and water for years",
      "Spread through irrigation water, soil on tools and boots, and infected seedlings",
      "Root wounds from cultivation or nematodes let the bacteria in",
      "Warm wet soil speeds up multiplication",
    ],
    weather: ["Warm and humid", "Waterlogged soil", "Heavy rain"],
    weatherNote:
      "Worst in warm soils above 24°C that stay wet, which is why it peaks in the rainy season.",
    plants: ["Tomato", "Potato", "Eggplant", "Banana", "Ginger", "Chilli"],
    severity: "Very High",
    difficulty: "Hard",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Never plant tomato-family crops in a field with a wilt history",
      "Use resistant rootstocks and grafted seedlings where available",
      "Raise beds so water drains away from the root zone",
      "Disinfect tools, boots and stakes between fields",
      "Control root-knot nematodes, which open the door for the bacteria",
    ],
    organic: [
      "Remove infected plants with the surrounding soil and destroy them away from the field",
      "Long rotation with cereals or maize, three years or more",
      "Soil solarisation with clear plastic in the hot season",
      "Add well-rotted compost to build competing soil life",
    ],
    chemical: [
      "There is no reliable chemical cure once plants are infected",
      "Soil fumigation is used in some commercial systems but is expensive and tightly regulated",
      "Budget for clean seedlings, grafting and drainage instead of sprays",
    ],
    practices: [
      "Irrigate infected blocks last so water does not carry bacteria to clean areas",
      "Map wilt patches every year and rotate accordingly",
      "Avoid moving soil between fields on machinery",
    ],
    tags: ["sudden wilt", "green wilt", "stem ooze", "ralstonia", "soil borne"],
    related: ["fusarium-wilt", "root-rot", "bacterial-leaf-spot", "nematodes"],
    reviewed: "2026-07-22",
    added: "2026-07-19",
    popularity: 76,
  },
  {
    slug: "bacterial-leaf-spot",
    name: "Bacterial Leaf Spot",
    scientificName: "Xanthomonas and Pseudomonas species",
    category: "disease",
    kind: "Bacterial",
    image: "bacterial",
    summary:
      "Small dark, greasy-looking spots that are squared off by leaf veins. Fungicides do not touch it, so prevention matters most.",
    identification: [
      "Spots look wet or oily, especially early in the morning.",
      "Edges are angular because the veins stop the spread.",
      "A yellow halo often rings the spot.",
      "Held to the light, young spots look translucent.",
    ],
    symptoms: [
      "Dark angular spots 1-3 mm across on leaves",
      "Spots merging into large dead patches and heavy leaf drop",
      "Raised scabby spots on fruit that reduce market value",
      "Blackened flower stalks in some crops",
    ],
    causes: [
      "Infected seed and transplants are the most common starting point",
      "Rain splash, overhead irrigation and wind-driven rain move bacteria",
      "Handling wet plants transfers bacteria across a whole row",
      "Warm humid weather multiplies the population quickly",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote:
      "Ideal at 25-30°C with driving rain; storms that bruise leaves cause the sharpest outbreaks.",
    plants: ["Pepper", "Tomato", "Lettuce", "Cabbage", "Cotton", "Ornamentals"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Use certified seed or treat seed with hot water where advised",
      "Rotate away from the same family for two years",
      "Switch to drip irrigation instead of overhead sprinklers",
      "Stay out of the field until foliage is dry",
    ],
    organic: [
      "Remove badly infected plants rather than trying to save them",
      "Copper sprays applied protectively, starting before the rains",
      "Wide spacing and windbreaks to reduce leaf injury",
    ],
    chemical: [
      "Copper products, often combined with mancozeb, are the standard field option",
      "Some regions register bactericides or plant defence activators such as acibenzolar-S-methyl",
      "Fungicides alone will not work; confirm the cause first",
    ],
    practices: [
      "Discard the whole seedling tray if spots appear in the nursery",
      "Bury crop residue deeply after harvest",
      "Keep records of which seed lot was used in each block",
    ],
    tags: ["angular spots", "greasy spots", "xanthomonas", "pepper", "copper spray"],
    related: ["leaf-spot", "bacterial-wilt", "black-rot", "early-blight"],
    reviewed: "2026-07-22",
    added: "2026-07-19",
    popularity: 70,
  },
  {
    slug: "root-rot",
    name: "Root Rot",
    scientificName: "Pythium, Phytophthora and Rhizoctonia species",
    category: "disease",
    kind: "Soil-borne",
    image: "soil-root",
    summary:
      "Roots die in wet, airless soil, so the plant starves for water even though the ground is soaked.",
    identification: [
      "Pull up a plant: healthy roots are white and firm, rotted roots are brown and mushy.",
      "The outer root skin slips off, leaving a thin thread inside.",
      "A sour or musty smell from the root ball.",
      "Wilting at midday even though the soil is wet.",
    ],
    symptoms: [
      "Yellowing lower leaves and general stunting",
      "Wilting that does not respond to more watering",
      "Brown, soft, sparse roots with few fine feeder roots",
      "Dark rot at the crown or stem base",
      "Patches of poor plants in the lowest parts of the field",
    ],
    causes: [
      "Waterlogged, compacted soil with no oxygen for roots",
      "Overwatering and blocked drainage",
      "Pathogens carried in unsterile potting media or reused trays",
      "Planting too deep or piling mulch against the stem",
    ],
    weather: ["Waterlogged soil", "Heavy rain", "Cool and wet"],
    weatherNote:
      "Follows long wet spells and flooding, and is worse in heavy clay soils that hold water.",
    plants: ["Most vegetables", "Citrus", "Avocado", "Beans", "Potted plants"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Winter"],
    prevention: [
      "Plant on raised beds or ridges in heavy soils",
      "Break compaction and add organic matter to improve drainage",
      "Water when the top few centimetres of soil are dry, not on a fixed schedule",
      "Use clean trays and fresh media in nurseries",
    ],
    organic: [
      "Lift affected plants and improve drainage before replanting",
      "Add compost and beneficial fungi such as Trichoderma to the planting hole",
      "Avoid mulching right up against the stem",
    ],
    chemical: [
      "Oomycete products such as metalaxyl or phosphonates as a soil drench where registered",
      "Chemicals rarely help if the drainage problem is not fixed first",
    ],
    practices: [
      "Check soil moisture with a finger or probe before irrigating",
      "Grade fields so water leaves quickly after storms",
      "Do not reuse soil from a crop that collapsed with rot",
    ],
    tags: ["brown roots", "overwatering", "waterlogging", "wilting wet soil", "pythium"],
    related: ["damping-off", "fusarium-wilt", "bacterial-wilt", "late-blight"],
    reviewed: "2026-07-23",
    added: "2026-07-20",
    popularity: 83,
  },
  {
    slug: "fusarium-wilt",
    name: "Fusarium Wilt",
    scientificName: "Fusarium oxysporum",
    category: "disease",
    kind: "Soil-borne",
    image: "soil-root",
    summary:
      "A long-lived soil fungus that plugs the stem's water channels. Yellowing usually starts on one side of the plant.",
    identification: [
      "Yellowing and wilting often on one side or one branch first.",
      "Cutting the stem lengthwise shows brown streaks inside.",
      "No slimy ooze, which separates it from bacterial wilt.",
      "Lower leaves go first and the wilt creeps upward over weeks.",
    ],
    symptoms: [
      "One-sided leaf yellowing and drooping",
      "Brown discolouration in the stem's inner tissue",
      "Slow decline rather than overnight collapse",
      "Stunted plants with small fruit",
      "Dead plants in the same spots year after year",
    ],
    causes: [
      "Resting spores survive in soil for a decade or more",
      "Specialised strains attack particular crops such as banana, tomato or cotton",
      "Movement of infested soil, water and planting material",
      "Warm soil and acidic, low-organic-matter conditions favour it",
    ],
    weather: ["Hot and dry", "Warm and humid"],
    weatherNote:
      "Most damaging in warm soils of 25-30°C, and symptoms show fastest when plants are water-stressed.",
    plants: ["Tomato", "Banana", "Cotton", "Watermelon", "Chickpea", "Cucumber"],
    severity: "Very High",
    difficulty: "Hard",
    seasons: ["Summer", "Monsoon"],
    prevention: [
      "Plant resistant varieties, which are the single most effective tool",
      "Use grafted seedlings on resistant rootstock for tomato and melon",
      "Keep clean field hygiene: no soil sharing between blocks",
      "Raise soil pH slightly and add organic matter where advice supports it",
    ],
    organic: [
      "Long rotations with non-host crops such as cereals",
      "Soil solarisation during the hottest months",
      "Trichoderma and other biocontrol agents applied at planting",
      "Remove and burn infected plants with their root balls",
    ],
    chemical: [
      "No effective curative chemical for an infected plant",
      "Soil fumigation exists commercially but is costly and strictly regulated",
      "Invest in resistant varieties and rotation instead",
    ],
    practices: [
      "Keep a field map of wilt spots and avoid replanting hosts there",
      "Sanitise machinery when moving between farms",
      "Buy planting material only from certified nurseries",
    ],
    tags: ["one sided yellowing", "vascular wilt", "banana panama disease", "fusarium"],
    related: ["bacterial-wilt", "root-rot", "damping-off", "nematodes"],
    reviewed: "2026-07-23",
    added: "2026-07-20",
    popularity: 72,
  },
  {
    slug: "cercospora-leaf-spot",
    name: "Cercospora Leaf Spot",
    scientificName: "Cercospora species",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Grey-centred spots with a dark red or purple border, common on beet, groundnut, chilli and banana.",
    identification: [
      "Round spots with an ash-grey centre and a distinct dark ring.",
      "Centres may fall out and leave holes.",
      "Spots stay small and separate before joining late in the season.",
      "In banana, long dark streaks run along the leaf.",
    ],
    symptoms: [
      "Numerous small spots peppering the leaf surface",
      "Leaves turning brown and dying from the bottom up",
      "Reduced root and fruit size from lost leaf area",
      "Repeated defoliation and regrowth that exhausts the plant",
    ],
    causes: [
      "Fungus overwinters on residue and seed",
      "Spores spread by wind, rain splash and irrigation",
      "Dense canopies and high humidity extend leaf wetness",
      "Continuous cropping without rotation",
    ],
    weather: ["Warm and humid", "Heavy rain", "Dew and fog"],
    weatherNote:
      "Needs warm nights above 16°C with high humidity; long dew periods drive repeated infection cycles.",
    plants: ["Sugar beet", "Groundnut", "Banana", "Chilli", "Carrot", "Okra"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Rotate for two to three years with non-host crops",
      "Use tolerant varieties and clean, treated seed",
      "Avoid overhead irrigation late in the day",
      "Space rows to let the canopy dry",
    ],
    organic: [
      "Remove lower infected leaves early in the epidemic",
      "Copper sprays as a protective cover in wet weather",
      "Bury residue deeply after harvest",
    ],
    chemical: [
      "Protectants such as mancozeb combined with triazoles in commercial fields",
      "Strobilurins work well but resistance is already widespread in some regions",
      "Follow a spray threshold based on scouting, not the calendar",
    ],
    practices: [
      "Scout for the first spots on the oldest leaves weekly",
      "Rotate chemical groups strictly in this pathogen; it adapts fast",
      "Keep field records so you can start sprays at the same growth stage next year",
    ],
    tags: ["grey centre spots", "purple border", "beet", "banana sigatoka", "groundnut"],
    related: ["septoria-leaf-spot", "alternaria-leaf-spot", "leaf-spot", "early-blight"],
    reviewed: "2026-07-24",
    added: "2026-07-21",
    popularity: 64,
  },
  {
    slug: "alternaria-leaf-spot",
    name: "Alternaria Leaf Spot",
    scientificName: "Alternaria species",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Dark brown spots with faint rings on cabbage-family crops, oilseeds and many vegetables, often after warm rain.",
    identification: [
      "Brown to black spots with light rings inside.",
      "A sooty layer of spores may cover the spot centre in humid weather.",
      "Yellow halo around larger spots.",
      "On cabbage and cauliflower, spots also appear on the heads.",
    ],
    symptoms: [
      "Circular dark spots that expand and merge",
      "Yellowing and early loss of the oldest leaves",
      "Spotting on heads, pods and seed that lowers grade",
      "Weak seedlings when infected seed is used",
    ],
    causes: [
      "Seed-borne infection and infected crop residue",
      "Warm humid weather with frequent light rain",
      "Nutrient stress, especially low nitrogen or potassium",
      "Tight planting with poor airflow",
    ],
    weather: ["Warm and humid", "Heavy rain", "Dew and fog"],
    weatherNote: "Sporulates heavily at 20-30°C with humidity above 90% and repeated dew.",
    plants: ["Cabbage", "Cauliflower", "Mustard", "Tomato", "Potato", "Carrot"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Winter", "Monsoon", "Spring"],
    prevention: [
      "Sow certified, treated seed",
      "Rotate away from brassicas and tomato-family crops",
      "Control cruciferous weeds around the field",
      "Feed a balanced fertiliser, not nitrogen alone",
    ],
    organic: [
      "Remove infected lower leaves and destroy them",
      "Copper or Bacillus subtilis products applied protectively",
      "Warm-water seed treatment where local guidance supports it",
    ],
    chemical: [
      "Mancozeb, chlorothalonil or difenoconazole are commonly used",
      "Start at first spot and repeat according to the label in wet weather",
      "Observe the pre-harvest interval on leafy vegetables carefully",
    ],
    practices: [
      "Do not save seed from a spotted crop",
      "Clear crop residue promptly after harvest",
      "Harvest heads before spots reach the marketable part",
    ],
    tags: ["brown spots", "cabbage", "mustard", "rings", "alternaria"],
    related: ["early-blight", "cercospora-leaf-spot", "septoria-leaf-spot", "black-rot"],
    reviewed: "2026-07-24",
    added: "2026-07-21",
    popularity: 61,
  },
  {
    slug: "septoria-leaf-spot",
    name: "Septoria Leaf Spot",
    scientificName: "Septoria lycopersici and Zymoseptoria tritici",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Many small circular spots with pale centres and tiny black dots. It strips tomato plants from the bottom upward.",
    identification: [
      "Small spots, 2-5 mm, with grey or tan centres and dark edges.",
      "Tiny black pinhead dots inside the spot, visible with a hand lens.",
      "Far more spots per leaf than early blight, and no target rings.",
      "Starts on the lowest leaves after the first fruit sets.",
    ],
    symptoms: [
      "Dozens of small spots on the older leaves",
      "Rapid yellowing and total leaf loss from the base up",
      "Bare stems with fruit exposed to the sun",
      "In wheat, long tan blotches on leaves with black specks",
    ],
    causes: [
      "Fungus survives on residue, weeds in the tomato family, and stakes",
      "Rain and overhead irrigation splash spores upward",
      "Long wet periods and dense foliage",
      "Handling wet plants and moving spores on hands and clothes",
    ],
    weather: ["Warm and humid", "Heavy rain", "Dew and fog"],
    weatherNote:
      "Needs long leaf wetness at 20-25°C; several wet days in a row cause the sharpest jumps.",
    plants: ["Tomato", "Wheat", "Potato", "Celery"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Summer", "Winter"],
    prevention: [
      "Mulch heavily to stop soil splash",
      "Stake and prune the lowest leaves for airflow",
      "Rotate for two years and control nightshade weeds",
      "Disinfect stakes and cages between seasons",
    ],
    organic: [
      "Strip and destroy the first spotted leaves before spots multiply",
      "Copper sprays repeated after each heavy rain",
      "Bacillus-based biofungicides as a protective cover",
    ],
    chemical: [
      "Chlorothalonil and mancozeb are standard protectants in tomato",
      "Triazoles or SDHI products are used in cereals under resistance-management rules",
      "Keep new growth covered during a wet spell",
    ],
    practices: [
      "Scout the bottom third of the plant weekly",
      "Never compost infected tomato foliage in a cool heap",
      "Water at the base early in the day",
    ],
    tags: ["tiny black dots", "small spots", "tomato defoliation", "septoria", "wheat blotch"],
    related: ["early-blight", "cercospora-leaf-spot", "leaf-spot", "alternaria-leaf-spot"],
    reviewed: "2026-07-25",
    added: "2026-07-22",
    popularity: 79,
  },
  {
    slug: "black-rot",
    name: "Black Rot",
    scientificName: "Xanthomonas campestris pv. campestris / Guignardia bidwellii",
    category: "disease",
    kind: "Bacterial",
    image: "bacterial",
    summary:
      "In cabbage-family crops, a bacterium that turns leaf edges into yellow V-shapes with black veins. In grapes, a fungus that mummifies berries.",
    identification: [
      "Yellow V-shaped wedges starting at the leaf edge, pointing inward.",
      "Veins inside the wedge turn black.",
      "Cut stems show a black ring.",
      "In grapes, brown leaf spots with black dots, and berries that shrivel into hard black mummies.",
    ],
    symptoms: [
      "V-shaped yellow-brown lesions on brassica leaves",
      "Black vein network visible against the light",
      "Head rot with a foul smell when secondary rots join in",
      "Grape clusters drying into hard black mummies",
    ],
    causes: [
      "Contaminated seed and infected transplants",
      "Splashing rain and irrigation moving bacteria into leaf pores and wounds",
      "Insect and hail damage giving entry points",
      "Warm humid weather during head formation",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote:
      "Fastest at 25-30°C with wet leaves; grape black rot peaks in warm rainy spells around flowering.",
    plants: ["Cabbage", "Cauliflower", "Broccoli", "Kale", "Grape"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Winter", "Spring"],
    prevention: [
      "Use hot-water treated or certified seed for brassicas",
      "Rotate at least two years away from the same family",
      "Remove mummified grape berries and infected canes in winter",
      "Avoid working the crop when leaves are wet",
    ],
    organic: [
      "Rogue out infected seedlings from nursery trays immediately",
      "Copper sprays as protection during rainy periods",
      "Clean up all crop residue after harvest",
    ],
    chemical: [
      "Copper-based products for the bacterial form in brassicas",
      "Mancozeb or myclobutanil programmes for grape black rot from bud break",
      "Fungicides do not control the bacterial form, so identify it first",
    ],
    practices: [
      "Inspect every nursery batch before transplanting",
      "Prune grapes for an open canopy that dries quickly",
      "Keep detailed spray and seed-lot records",
    ],
    tags: ["v shaped lesion", "black veins", "cabbage", "grape mummies", "xanthomonas"],
    related: ["bacterial-leaf-spot", "anthracnose", "alternaria-leaf-spot", "canker"],
    reviewed: "2026-07-25",
    added: "2026-07-22",
    popularity: 63,
  },
  {
    slug: "scab",
    name: "Scab",
    scientificName: "Venturia inaequalis / Streptomyces scabies",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Rough, corky patches on fruit, leaves or tubers. Rarely kills the plant but badly damages market quality.",
    identification: [
      "Olive-green velvety spots on apple leaves that turn brown and corky.",
      "Cracked, scabby patches on the fruit skin.",
      "On potato, raised or pitted rough patches on the tuber surface.",
      "Damage is skin-deep; the flesh underneath is usually sound.",
    ],
    symptoms: [
      "Dull olive spots on the upper leaf surface early in the season",
      "Distorted, cracked fruit that will not store well",
      "Early leaf drop in apple and pear",
      "Rough corky patches lowering the grade of potato tubers",
    ],
    causes: [
      "Apple scab overwinters in fallen leaves and releases spores in spring rain",
      "Potato scab bacteria thrive in dry alkaline soils during tuber formation",
      "Long spring wet periods during leaf emergence",
      "Susceptible varieties and dense unpruned canopies",
    ],
    weather: ["Cool and wet", "Heavy rain", "Mild and dry"],
    weatherNote:
      "Apple scab needs spring rain at 15-24°C; potato scab is the opposite, worsening in dry soil during tuber set.",
    plants: ["Apple", "Pear", "Potato", "Citrus", "Cucumber"],
    severity: "Medium",
    difficulty: "Moderate",
    seasons: ["Spring", "Summer"],
    prevention: [
      "Plant scab-resistant apple varieties",
      "Rake up and destroy fallen leaves in winter",
      "Prune for an open canopy that dries fast",
      "For potato, keep soil evenly moist during tuber formation and avoid liming before a potato crop",
    ],
    organic: [
      "Sulphur or lime-sulphur sprays timed with spring rain events",
      "Shred fallen leaves to speed up their breakdown",
      "Green manure and rotation with cereals for potato scab",
    ],
    chemical: [
      "Protectant sprays such as captan or mancozeb from bud break in apples",
      "Systemic products such as difenoconazole during high-risk rain periods",
      "No effective chemical control for potato scab; manage soil moisture instead",
    ],
    practices: [
      "Follow local scab warning models where they exist",
      "Grade fruit at harvest so scabby fruit does not enter storage",
      "Rotate potato with cereals for two to three years",
    ],
    tags: ["corky patches", "apple scab", "potato scab", "rough skin", "venturia"],
    related: ["powdery-mildew", "anthracnose", "black-rot", "canker"],
    reviewed: "2026-07-26",
    added: "2026-07-23",
    popularity: 58,
  },
  {
    slug: "canker",
    name: "Canker and Dieback",
    scientificName: "Nectria, Botryosphaeria, Xanthomonas citri and others",
    category: "disease",
    kind: "Fungal",
    image: "fungal-spot",
    summary:
      "Sunken dead patches on bark or stems that slowly strangle a branch. Common in trees and woody crops after wounding.",
    identification: [
      "Sunken, cracked bark with a raised edge where the tree fights back.",
      "Gum, resin or dark ooze seeping from the wound.",
      "Leaves above the canker wilt and die while the rest of the tree looks fine.",
      "On citrus, raised corky spots with a yellow halo on leaves and fruit.",
    ],
    symptoms: [
      "Sunken discoloured lesions on trunk or branches",
      "Dieback of shoots beyond the canker",
      "Cracked bark peeling away from dead wood",
      "Ooze or gumming at the lesion edge",
      "Whole limb death after girdling",
    ],
    causes: [
      "Pathogens entering through pruning cuts, hail, frost or insect wounds",
      "Trees stressed by drought, waterlogging or poor nutrition",
      "Wet weather at pruning time",
      "Infected planting material or contaminated pruning tools",
    ],
    weather: ["Cool and wet", "Heavy rain", "Waterlogged soil"],
    weatherNote:
      "Infection mostly happens in wet weather; damage becomes visible when the tree is under summer stress.",
    plants: ["Citrus", "Apple", "Mango", "Stone fruit", "Poplar", "Rose"],
    severity: "High",
    difficulty: "Hard",
    seasons: ["Winter", "Spring", "Monsoon"],
    prevention: [
      "Prune in dry weather and never just before rain",
      "Disinfect pruning tools between trees",
      "Avoid trunk injury from machinery and strimmers",
      "Keep trees well watered and fed so they can wall off wounds",
    ],
    organic: [
      "Cut out the canker back into healthy wood and burn the prunings",
      "Paint large cuts only where local practice recommends it",
      "Copper sprays at leaf fall and bud break for bacterial cankers",
    ],
    chemical: [
      "Copper programmes are standard for citrus canker where the disease is not under quarantine",
      "Fungicide paints and systemic trunk treatments exist for some orchard cankers",
      "Regulations may require destruction of infected trees; check local rules first",
    ],
    practices: [
      "Inspect trunks and scaffolds during winter pruning each year",
      "Remove dead wood promptly, do not leave stubs",
      "Buy nursery trees only from certified sources",
    ],
    tags: ["sunken bark", "dieback", "gumming", "citrus canker", "tree wound"],
    related: ["anthracnose", "black-rot", "root-rot", "scab"],
    reviewed: "2026-07-26",
    added: "2026-07-23",
    popularity: 55,
  },
  {
    slug: "damping-off",
    name: "Damping Off",
    scientificName: "Pythium, Rhizoctonia and Fusarium species",
    category: "disease",
    kind: "Soil-borne",
    image: "soil-root",
    summary:
      "Seedlings collapse at soil level and fall over. The most common reason a nursery tray fails.",
    identification: [
      "A thin, dark, pinched section of stem right at the soil line.",
      "Seedlings topple over but the leaves still look green at first.",
      "Failures appear in circular patches that spread outward.",
      "Some seeds rot before they even emerge.",
    ],
    symptoms: [
      "Patchy or failed emergence",
      "Water-soaked pinched stems at the soil surface",
      "Seedlings falling flat overnight",
      "White fungal threads on the soil surface in humid trays",
    ],
    causes: [
      "Overwatering and soil that never dries between waterings",
      "Reused trays, dirty tools and unsterilised media",
      "Sowing too thickly with poor airflow",
      "Cold wet soil that slows germination and gives pathogens time",
    ],
    weather: ["Cool and wet", "Waterlogged soil", "Poor airflow"],
    weatherNote:
      "Worst when soil is wet and cooler than ideal for the crop, so germination is slow.",
    plants: ["All seedlings", "Tomato", "Cabbage", "Chilli", "Cucumber", "Flowers"],
    severity: "High",
    difficulty: "Easy",
    seasons: ["Spring", "Winter", "Monsoon"],
    prevention: [
      "Use fresh, well-drained seed-starting mix",
      "Wash and disinfect trays and tools before each batch",
      "Sow thinly and thin early to give each seedling air",
      "Water in the morning and let the surface dry between waterings",
      "Provide gentle airflow with a fan in enclosed nurseries",
    ],
    organic: [
      "Sprinkle a thin layer of dry sand or vermiculite on the surface to keep stems dry",
      "Trichoderma or Bacillus biological drenches at sowing",
      "Remove collapsed seedlings and their soil at once",
      "Weak chamomile or cinnamon drenches are traditional home remedies with modest effect",
    ],
    chemical: [
      "Seed treatment with a registered fungicide is the most reliable option",
      "Drenches based on metalaxyl or thiram are used commercially",
      "Correct watering and hygiene fix most cases without any chemical",
    ],
    practices: [
      "Never reuse soil from a tray that damped off",
      "Bottom-water trays instead of splashing overhead",
      "Harden seedlings gradually before transplanting",
    ],
    tags: ["seedling collapse", "nursery failure", "pinched stem", "overwatering", "pythium"],
    related: ["root-rot", "fusarium-wilt", "cutworms", "healthy-leaf-guide"],
    reviewed: "2026-07-27",
    added: "2026-07-24",
    popularity: 80,
  },
  {
    slug: "healthy-leaf-guide",
    name: "Healthy Leaf Guide",
    scientificName: "Reference guide, no pathogen",
    category: "disease",
    kind: "Reference",
    image: "healthy",
    summary:
      "Know what healthy looks like first. Most misdiagnosis happens because normal ageing or nutrient problems are mistaken for disease.",
    identification: [
      "Even colour for the crop, with no mottling or pale patches between veins.",
      "Firm, flat surface with no puckering, curling or cupping.",
      "Clean underside with no fuzz, webbing or insect colonies.",
      "New growth appearing at a steady rate at the top of the plant.",
    ],
    symptoms: [
      "Not a disease: this card describes the healthy baseline",
      "Old bottom leaves yellowing slowly is normal ageing, not blight",
      "Yellow between green veins usually means a nutrient issue, not infection",
      "Uniform pale colour across the whole plant often means nitrogen shortage",
      "Crisp brown edges usually mean salt or water stress, not a pathogen",
    ],
    causes: [
      "Balanced nutrition and steady soil moisture",
      "Enough sunlight for the crop",
      "Good drainage and living soil",
      "Airflow that dries leaves within a few hours of rain or dew",
    ],
    weather: ["Mild and dry", "Warm and humid"],
    weatherNote:
      "Healthy plants tolerate a wide range, but sudden swings in heat, water or light cause stress symptoms that look like disease.",
    plants: ["All plants"],
    severity: "Low",
    difficulty: "Easy",
    seasons: ["All year"],
    prevention: [
      "Photograph each crop when it is healthy so you have a comparison later",
      "Test soil once a season and correct nutrients rather than guessing",
      "Water deeply and less often to build deep roots",
      "Scout weekly, checking leaf undersides as well as tops",
    ],
    organic: [
      "Compost and mulch to build steady soil health",
      "Encourage beneficial insects with flowering field borders",
      "Rotate crops so no family stays in one bed",
    ],
    chemical: [
      "No treatment needed for a healthy plant",
      "Never spray preventatively without an identified target: it wastes money and harms beneficial insects",
    ],
    practices: [
      "Keep a simple scan log with dates so you can see trends",
      "Compare a suspect leaf with a healthy leaf from the same plant",
      "Rule out watering, nutrition and sunburn before assuming disease",
    ],
    tags: ["healthy", "baseline", "nutrient deficiency", "normal ageing", "how to check"],
    related: ["leaf-spot", "root-rot", "mosaic-virus", "spider-mites"],
    reviewed: "2026-07-27",
    added: "2026-07-24",
    popularity: 90,
  },
];
