import type { KnowledgeEntry } from "./types";

/**
 * Pest notes summarised in plain English from public integrated pest
 * management guidance (see SOURCES in ./sources.ts). Chemical notes are
 * general orientation only: pesticide registration differs by country.
 */
export const PESTS: KnowledgeEntry[] = [
  {
    slug: "aphids",
    name: "Aphids",
    scientificName: "Aphis, Myzus and related genera",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Soft pear-shaped insects that cluster on new shoots, suck sap and pass plant viruses from field to field.",
    identification: [
      "Dense colonies on the youngest shoots and leaf undersides.",
      "Two small tubes stick out from the rear of the body.",
      "Green, black, grey, pink or yellow depending on species.",
      "Shiny sticky honeydew below the colony, often with ants walking on it.",
    ],
    symptoms: [
      "Curled, cupped or twisted young leaves",
      "Sticky honeydew that turns into black sooty mould",
      "Stunted shoots and deformed flower buds",
      "Yellow mottling from viruses the aphids carry",
      "White shed skins scattered on leaves below the colony",
    ],
    causes: [
      "Soft lush growth from heavy nitrogen feeding",
      "Mild weather with no natural enemies present",
      "Ants protecting colonies from predators",
      "Weedy field edges that host aphids between crops",
    ],
    weather: ["Mild and dry", "Warm and humid"],
    weatherNote:
      "Populations explode at 18-26°C; heavy rain knocks colonies off plants and very hot dry weather slows them.",
    plants: ["Most vegetables", "Cotton", "Wheat", "Citrus", "Rose", "Mustard"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Spring", "Autumn", "Winter"],
    prevention: [
      "Avoid excess nitrogen that produces soft sappy growth",
      "Keep flowering borders to feed ladybirds, lacewings and hoverflies",
      "Use reflective mulch in young crops to confuse flying aphids",
      "Control ants, which farm and protect aphid colonies",
    ],
    organic: [
      "A firm jet of water knocks colonies off sturdy plants",
      "Insecticidal soap or neem oil sprayed onto the leaf underside",
      "Release or protect ladybird larvae and parasitic wasps",
      "Pinch out and destroy the worst infested shoot tips",
    ],
    chemical: [
      "Selective options such as flonicamid or pymetrozine spare most beneficial insects",
      "Broad-spectrum sprays often make things worse by killing predators",
      "Rotate modes of action; aphids develop resistance fast",
    ],
    practices: [
      "Scout the growing tips twice weekly and count colonies",
      "Only treat when numbers pass the local action threshold",
      "Protect seed crops especially, because of virus spread",
    ],
    tags: ["greenfly", "blackfly", "honeydew", "curled leaves", "sooty mould", "virus vector"],
    related: ["whiteflies", "mealybugs", "mosaic-virus", "ants"],
    reviewed: "2026-07-15",
    added: "2026-07-15",
    popularity: 94,
  },
  {
    slug: "whiteflies",
    name: "Whiteflies",
    scientificName: "Bemisia tabaci, Trialeurodes vaporariorum",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Tiny white moth-like insects that fly up in a cloud when a plant is shaken. Major carriers of leaf curl viruses.",
    identification: [
      "Clouds of small white insects rising when leaves are disturbed.",
      "Oval scale-like young stages fixed to the leaf underside.",
      "Sticky leaves with black sooty mould.",
      "Damage concentrated on the youngest leaves.",
    ],
    symptoms: [
      "Yellowing, curling and silvering of leaves",
      "Sticky honeydew and sooty mould on lower foliage",
      "Stunted plants with poor fruit set",
      "Severe leaf curl and yellow vein symptoms from transmitted viruses",
    ],
    causes: [
      "Warm dry weather and protected greenhouse conditions",
      "Continuous cropping that never breaks the life cycle",
      "Infested transplants brought into a clean field",
      "Loss of natural enemies after broad-spectrum sprays",
    ],
    weather: ["Hot and dry", "Warm and humid"],
    weatherNote:
      "Breeding is fastest at 25-32°C; numbers crash in cold weather and heavy monsoon rain.",
    plants: ["Tomato", "Cotton", "Chilli", "Okra", "Cassava", "Beans", "Greenhouse crops"],
    severity: "High",
    difficulty: "Hard",
    seasons: ["Summer", "Autumn", "All year"],
    prevention: [
      "Inspect and quarantine every batch of transplants",
      "Use fine insect netting on nursery beds and greenhouse vents",
      "Grow virus-resistant varieties in high-pressure areas",
      "Keep a crop-free break to starve the population",
    ],
    organic: [
      "Yellow sticky traps for monitoring and light control",
      "Insecticidal soap, neem or horticultural oil on leaf undersides",
      "Release Encarsia parasitic wasps in greenhouses",
      "Remove and bag heavily infested lower leaves",
    ],
    chemical: [
      "Selective insect growth regulators such as pyriproxyfen or buprofezin",
      "Neonicotinoids are widely restricted; check local rules before use",
      "Strict rotation of modes of action is essential; resistance is common",
    ],
    practices: [
      "Count adults on sticky traps weekly and record the trend",
      "Destroy crop residue immediately after final harvest",
      "Treat the leaf underside; sprays on the top surface mostly miss",
    ],
    tags: ["white flies", "leaf curl virus", "sticky leaves", "greenhouse", "bemisia"],
    related: ["aphids", "thrips", "mosaic-virus", "mealybugs"],
    reviewed: "2026-07-16",
    added: "2026-07-15",
    popularity: 87,
  },
  {
    slug: "thrips",
    name: "Thrips",
    scientificName: "Thrips tabaci, Frankliniella occidentalis, Scirtothrips dorsalis",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Slender insects barely a millimetre long that rasp the leaf surface, leaving silvery scars and black specks.",
    identification: [
      "Silver or bronze streaks where the surface has been scraped.",
      "Tiny black dots of excrement beside the scars.",
      "Fast-moving slim insects hiding in flowers and leaf folds.",
      "Tap a flower over white paper to see them fall out.",
    ],
    symptoms: [
      "Silvery streaking and speckling on leaves",
      "Curled, upward-cupped leaves in chilli and cotton",
      "Deformed, scarred fruit and flower drop",
      "Bronze discolouration in onion tops",
      "Spotted wilt virus symptoms after feeding",
    ],
    causes: [
      "Hot dry weather with rapid generation turnover",
      "Weedy borders and nearby harvested crops pushing thrips into the field",
      "Overuse of broad-spectrum sprays that kill predatory mites",
      "Dusty conditions along field edges and tracks",
    ],
    weather: ["Hot and dry", "Mild and dry"],
    weatherNote:
      "Numbers rise sharply above 28°C in dry weather; heavy rain and overhead irrigation reduce them.",
    plants: ["Onion", "Chilli", "Cotton", "Mango", "Grape", "Beans", "Ornamentals"],
    severity: "High",
    difficulty: "Hard",
    seasons: ["Summer", "Spring"],
    prevention: [
      "Keep field borders weed-free before the crop emerges",
      "Avoid planting next to a crop about to be harvested",
      "Use blue sticky traps to detect early arrivals",
      "Irrigate adequately; drought-stressed crops suffer most",
    ],
    organic: [
      "Neem oil or spinosad products, applied to reach flowers and folds",
      "Predatory mites and minute pirate bugs in protected crops",
      "Overhead sprinkling during dry spells to disturb feeding",
    ],
    chemical: [
      "Spinetoram, cyantraniliprole and similar selective products where registered",
      "Thrips resist many older insecticides; rotate modes of action strictly",
      "Time sprays to newly hatched stages, not adults alone",
    ],
    practices: [
      "Sample flowers and young leaves weekly",
      "Remove crop residues that shelter pupae in the soil",
      "Do not spray flowering crops when bees are active",
    ],
    tags: ["silver streaks", "leaf curl", "onion bronzing", "tiny insects", "spotted wilt"],
    related: ["whiteflies", "spider-mites", "aphids", "mosaic-virus"],
    reviewed: "2026-07-16",
    added: "2026-07-16",
    popularity: 77,
  },
  {
    slug: "spider-mites",
    name: "Spider Mites",
    scientificName: "Tetranychus urticae and related species",
    category: "pest",
    kind: "Mite",
    image: "mite-pest",
    summary:
      "Dust-sized mites that thrive in hot dry weather, speckling leaves with pale dots and spinning fine webs.",
    identification: [
      "Fine pale stippling all over the leaf, like a light dusting of sand.",
      "Delicate webbing between leaf and stem in heavy attacks.",
      "Moving specks on the underside, visible with a hand lens.",
      "Tap a leaf over white paper: the specks crawl.",
    ],
    symptoms: [
      "Pale speckled leaves turning bronze or grey",
      "Fine webbing over shoot tips",
      "Leaf drop and reduced yield in hot spells",
      "Whole plants drying out in severe outbreaks",
    ],
    causes: [
      "Hot dry dusty conditions",
      "Loss of predatory mites after broad-spectrum insecticide use",
      "Water-stressed plants with concentrated sap",
      "Dusty roadside and greenhouse edges",
    ],
    weather: ["Hot and dry"],
    weatherNote:
      "Ideal above 30°C with low humidity; populations can double in under a week and collapse in wet weather.",
    plants: ["Beans", "Cotton", "Tomato", "Cucumber", "Strawberry", "Ornamentals"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Summer"],
    prevention: [
      "Keep plants properly watered; drought stress invites mites",
      "Damp down dusty paths and greenhouse floors",
      "Avoid unnecessary broad-spectrum insecticides that kill mite predators",
      "Inspect the underside of leaves weekly in hot weather",
    ],
    organic: [
      "Strong water sprays under the leaves to knock mites off",
      "Horticultural oil or insecticidal soap with full underside coverage",
      "Release predatory mites such as Phytoseiulus persimilis",
      "Remove and bag the worst leaves early",
    ],
    chemical: [
      "Specific miticides such as abamectin, spiromesifen or bifenazate where registered",
      "Most insecticides do not kill mites and can trigger a flare-up",
      "Rotate miticide groups; resistance appears very quickly",
    ],
    practices: [
      "Scout the leaf underside with a hand lens every week in summer",
      "Treat hot spots early instead of the whole field late",
      "Keep field edges mown and dust-free",
    ],
    tags: ["webbing", "stippling", "red spider", "hot dry", "hand lens"],
    related: ["thrips", "whiteflies", "aphids", "healthy-leaf-guide"],
    reviewed: "2026-07-17",
    added: "2026-07-16",
    popularity: 89,
  },
  {
    slug: "mealybugs",
    name: "Mealybugs",
    scientificName: "Planococcus and Pseudococcus species",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Soft insects wrapped in white waxy fluff that hide in leaf joints and root zones and are hard to reach with sprays.",
    identification: [
      "White cottony clusters in leaf axils, under leaves and on stems.",
      "Slow-moving oval insects under the wax.",
      "Sticky honeydew and black sooty mould below the colony.",
      "Ants running up and down the plant.",
    ],
    symptoms: [
      "Yellowing, wilting and leaf drop",
      "Stunted, distorted new growth",
      "Sooty mould blackening leaves and fruit",
      "White waxy deposits on roots in pot plants",
    ],
    causes: [
      "Infested planting material and pots moved between sites",
      "Warm sheltered conditions in greenhouses and indoor plants",
      "Ants transporting and defending colonies",
      "Overcrowded plants with poor airflow",
    ],
    weather: ["Warm and humid", "Mild and dry"],
    weatherNote:
      "Breeds all year in warm sheltered spots; outdoor numbers peak in warm dry seasons.",
    plants: ["Citrus", "Grape", "Cotton", "Mango", "Papaya", "Indoor plants"],
    severity: "Medium",
    difficulty: "Hard",
    seasons: ["All year", "Summer"],
    prevention: [
      "Inspect and isolate new plants for two weeks",
      "Control ants around the base of plants and trees",
      "Prune to open the canopy so sprays can reach hidden joints",
      "Clean pots, benches and stakes between crops",
    ],
    organic: [
      "Dab small colonies with an alcohol-soaked cotton bud",
      "Horticultural oil or soap sprays, repeated every 7-10 days",
      "Release Cryptolaemus beetles in greenhouses",
      "Cut out and destroy heavily infested shoots",
    ],
    chemical: [
      "Systemic products are sometimes needed because the wax repels contact sprays",
      "Buprofezin and spirotetramat are used in orchards where registered",
      "Repeat treatment is essential; one spray never clears a colony",
    ],
    practices: [
      "Check leaf joints and the underside of fruit clusters every week",
      "Treat ants and mealybugs together, never separately",
      "Discard badly infested pot plants rather than spreading them",
    ],
    tags: ["white cottony", "waxy", "sticky", "ants", "citrus", "houseplant"],
    related: ["scale-insects", "aphids", "whiteflies", "ants"],
    reviewed: "2026-07-17",
    added: "2026-07-17",
    popularity: 68,
  },
  {
    slug: "scale-insects",
    name: "Scale Insects",
    scientificName: "Coccidae and Diaspididae families",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Immobile bumps on stems and leaves that look like part of the plant. Only the young crawler stage moves.",
    identification: [
      "Small round or oval bumps, brown, grey or white, stuck to bark and leaves.",
      "Scrape one off: soft scales leave a moist insect body underneath.",
      "Sticky honeydew from soft scales, but none from armoured scales.",
      "Yellow spots on the leaf directly under each scale.",
    ],
    symptoms: [
      "Yellow spotting and general leaf yellowing",
      "Branch dieback in heavy infestations",
      "Sooty mould coating fruit and foliage",
      "Cracked bark and weakened young trees",
    ],
    causes: [
      "Infested nursery stock brought onto the farm",
      "Dusty, sheltered, unpruned canopies",
      "Loss of parasitic wasps after broad-spectrum sprays",
      "Ants protecting soft scale colonies",
    ],
    weather: ["Warm and humid", "Mild and dry"],
    weatherNote:
      "Crawlers emerge in warm spring and summer weather — that short window is when control works.",
    plants: ["Citrus", "Mango", "Guava", "Olive", "Tea", "Ornamental trees"],
    severity: "Medium",
    difficulty: "Hard",
    seasons: ["Spring", "Summer", "All year"],
    prevention: [
      "Inspect nursery trees carefully before planting",
      "Prune out and burn heavily encrusted branches",
      "Manage ants that protect the colonies",
      "Keep trees vigorous with proper irrigation and nutrition",
    ],
    organic: [
      "Horticultural oil sprays timed to the crawler stage",
      "Brush off scales on small plants with a soft brush and soapy water",
      "Protect natural parasitic wasps by avoiding blanket sprays",
    ],
    chemical: [
      "Insect growth regulators and systemic products used at crawler emergence",
      "Sprays applied to adult armoured scales are largely wasted",
      "Follow local orchard programmes and rotate modes of action",
    ],
    practices: [
      "Wrap sticky tape around a branch to detect crawler movement",
      "Time all treatment to that crawler window",
      "Prune for light and air every winter",
    ],
    tags: ["bumps on stem", "armoured scale", "sooty mould", "citrus", "crawlers"],
    related: ["mealybugs", "aphids", "ants", "whiteflies"],
    reviewed: "2026-07-18",
    added: "2026-07-17",
    popularity: 60,
  },
  {
    slug: "leaf-miners",
    name: "Leaf Miners",
    scientificName: "Liriomyza species and various moth larvae",
    category: "pest",
    kind: "Chewing insect",
    image: "miner-pest",
    summary:
      "Larvae that tunnel between the two skins of a leaf, leaving pale winding trails you can see against the light.",
    identification: [
      "Pale snaking tunnels that get wider along their length.",
      "A tiny dark line of droppings inside the tunnel.",
      "Holding the leaf up to light shows the larva at the tunnel end.",
      "Small white punctures where adult flies fed or laid eggs.",
    ],
    symptoms: [
      "White or brown winding mines across leaves",
      "Blotchy dead patches when several mines join",
      "Early leaf drop and sunburn on exposed fruit",
      "Reduced market value of leafy vegetables",
    ],
    causes: [
      "Adult flies laying eggs into leaf tissue",
      "Repeated broad-spectrum sprays killing parasitic wasps",
      "Continuous host cropping with no break",
      "Warm weather speeding up the life cycle",
    ],
    weather: ["Warm and humid", "Mild and dry"],
    weatherNote:
      "Generations complete in two to three weeks at 25-30°C, so numbers build quickly in warm seasons.",
    plants: ["Tomato", "Beans", "Cucumber", "Spinach", "Citrus", "Onion", "Ornamentals"],
    severity: "Medium",
    difficulty: "Moderate",
    seasons: ["Spring", "Summer", "Monsoon"],
    prevention: [
      "Remove and destroy mined leaves before larvae emerge",
      "Protect nursery beds with fine netting",
      "Avoid unnecessary sprays so parasitic wasps survive",
      "Plough in crop residue promptly after harvest",
    ],
    organic: [
      "Squash larvae inside the mine between finger and thumb",
      "Neem-based sprays reduce egg laying",
      "Yellow sticky traps to catch adult flies",
      "Encourage parasitic wasps, which often control miners on their own",
    ],
    chemical: [
      "Translaminar products such as abamectin or cyromazine reach larvae inside the leaf",
      "Contact sprays on the leaf surface do very little",
      "Rotate groups; Liriomyza develops resistance quickly",
    ],
    practices: [
      "Count mined leaves weekly and treat only over threshold",
      "Never spray on a calendar basis for miners",
      "Keep records of parasitic wasp activity before deciding to spray",
    ],
    tags: ["tunnels", "squiggly lines", "mines", "liriomyza", "leafy vegetables"],
    related: ["caterpillars", "thrips", "whiteflies", "leaf-spot"],
    reviewed: "2026-07-18",
    added: "2026-07-18",
    popularity: 66,
  },
  {
    slug: "caterpillars",
    name: "Caterpillars",
    scientificName: "Larvae of Lepidoptera",
    category: "pest",
    kind: "Chewing insect",
    image: "chewing-pest",
    summary:
      "Moth and butterfly larvae that chew large holes in leaves and bore into fruit and pods. The most visible group of crop pests.",
    identification: [
      "Ragged holes chewed from the leaf edge or middle.",
      "Dark pellets of droppings on lower leaves.",
      "Larvae with three pairs of true legs plus fleshy prolegs.",
      "Egg clusters or single eggs on the leaf underside.",
    ],
    symptoms: [
      "Large irregular holes and skeletonised leaves",
      "Bore holes in fruit, pods and cobs",
      "Cut or wilted shoot tips",
      "Frass, webbing and rolled leaves",
    ],
    causes: [
      "Adult moths flying in and laying eggs on the crop",
      "Warm weather speeding up development",
      "Nearby harvested crops pushing larvae into the new field",
      "Loss of natural enemies from heavy spray use",
    ],
    weather: ["Warm and humid", "Mild and dry"],
    weatherNote: "Egg-laying peaks in warm calm nights; development is fastest at 25-30°C.",
    plants: ["Cabbage", "Tomato", "Maize", "Cotton", "Rice", "Chickpea", "Fruit trees"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Summer", "Monsoon", "Autumn"],
    prevention: [
      "Hang pheromone traps to detect moth flights early",
      "Use insect netting on small high-value plots",
      "Rotate crops and destroy residue that hides pupae",
      "Plant flowering borders to support parasitic wasps",
    ],
    organic: [
      "Hand-pick larvae and egg masses in small plots",
      "Bacillus thuringiensis sprays, which only affect caterpillars",
      "Neem-based products against very young larvae",
      "Release Trichogramma egg parasitoids where available",
    ],
    chemical: [
      "Selective products such as chlorantraniliprole, emamectin benzoate or spinosad",
      "Treat while larvae are small; large larvae inside fruit cannot be reached",
      "Rotate modes of action every generation",
    ],
    practices: [
      "Scout twice weekly and count larvae per plant",
      "Spray in the evening when larvae feed and bees are inactive",
      "Track pheromone trap catches to time treatment",
    ],
    tags: ["holes in leaves", "worms", "bollworm", "larvae", "chewing", "moth"],
    related: ["armyworms", "cutworms", "stem-borers", "leaf-miners"],
    reviewed: "2026-07-19",
    added: "2026-07-18",
    popularity: 91,
  },
  {
    slug: "armyworms",
    name: "Armyworms",
    scientificName: "Spodoptera species, including fall armyworm",
    category: "pest",
    kind: "Chewing insect",
    image: "chewing-pest",
    summary:
      "Caterpillars that arrive in waves and can strip a maize field in days. Fall armyworm is now a global threat.",
    identification: [
      "Larvae with light stripes down the body and an inverted Y mark on the head.",
      "Four dark spots in a square on the second-to-last body segment.",
      "Windowpane damage and ragged holes in the maize whorl.",
      "Moist sawdust-like frass packed into the whorl.",
    ],
    symptoms: [
      "Papery translucent patches on young leaves",
      "Large ragged holes and shredded whorls",
      "Frass filling the growing point",
      "Damaged cobs and reduced grain fill",
      "Whole young plants cut down in a heavy attack",
    ],
    causes: [
      "Adult moths migrating long distances on wind",
      "Continuous maize cropping providing year-round hosts",
      "Warm conditions supporting several generations a season",
      "Sprays that remove natural enemies",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote: "Egg laying follows warm humid nights, often after the first monsoon rains.",
    plants: ["Maize", "Rice", "Sorghum", "Cotton", "Vegetables", "Pasture grass"],
    severity: "Very High",
    difficulty: "Hard",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Plant early and uniformly across the area to escape peak flights",
      "Intercrop maize with legumes such as beans, which reduces attack",
      "Handle volunteer maize and grassy weeds between seasons",
      "Use pheromone traps to know when flights begin",
    ],
    organic: [
      "Hand-pick egg masses and young larvae from whorls",
      "Apply sand, ash or Bt granules directly into the whorl",
      "Bacillus thuringiensis or Metarhizium biopesticides",
      "Encourage birds and parasitic wasps around the field",
    ],
    chemical: [
      "Selective products such as chlorantraniliprole, spinetoram or emamectin benzoate",
      "Direct the spray into the whorl in the early morning or evening",
      "Rotate modes of action; resistance is already reported in many countries",
    ],
    practices: [
      "Scout 10 plants in five spots twice a week from emergence",
      "Treat when about one in five plants shows fresh whorl damage",
      "Report new outbreaks to local extension services",
    ],
    tags: ["fall armyworm", "maize whorl", "inverted y", "frass", "spodoptera"],
    related: ["caterpillars", "cutworms", "stem-borers", "grasshoppers"],
    reviewed: "2026-07-19",
    added: "2026-07-19",
    popularity: 86,
  },
  {
    slug: "fruit-flies",
    name: "Fruit Flies",
    scientificName: "Bactrocera and Ceratitis species",
    category: "pest",
    kind: "Chewing insect",
    image: "chewing-pest",
    summary:
      "Flies that lay eggs inside ripening fruit. The maggots feed inside, so the damage is hidden until the fruit rots.",
    identification: [
      "Small puncture marks with a sunken halo on the fruit skin.",
      "Ooze or gum weeping from the puncture.",
      "White legless maggots inside when the fruit is cut open.",
      "Fruit softening and dropping early.",
    ],
    symptoms: [
      "Premature fruit fall",
      "Brown soft patches spreading from the sting mark",
      "Maggots and rot inside apparently sound fruit",
      "Entire harvest rejected at market inspection",
    ],
    causes: [
      "Adults laying eggs into ripening fruit",
      "Fallen infested fruit left on the ground to recycle the pest",
      "Overlapping fruiting seasons of many host plants",
      "Warm weather producing many generations",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote: "Populations peak in warm humid weather during the main fruit ripening season.",
    plants: ["Mango", "Guava", "Citrus", "Cucurbits", "Papaya", "Chilli"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Summer", "Monsoon"],
    prevention: [
      "Collect and destroy every fallen fruit, twice a week",
      "Bag individual fruits on small trees",
      "Harvest slightly early where the crop allows",
      "Coordinate control with neighbouring orchards",
    ],
    organic: [
      "Protein bait traps mixed with an approved killing agent",
      "Methyl eugenol or cue-lure male traps to monitor and mass-trap",
      "Bury infested fruit at least 50 cm deep or solarise it in sealed bags",
      "Keep poultry under trees to eat pupating larvae",
    ],
    chemical: [
      "Spot bait sprays on tree trunks rather than whole-canopy cover sprays",
      "Cover sprays are rarely justified and harm pollinators",
      "Follow local quarantine and pre-harvest interval rules strictly",
    ],
    practices: [
      "Maintain traps all season and record catches",
      "Never leave culled fruit in a heap near the orchard",
      "Sort fruit carefully before packing to protect the whole consignment",
    ],
    tags: ["maggots in fruit", "sting marks", "mango", "guava", "bactrocera", "traps"],
    related: ["anthracnose", "beetles", "caterpillars", "weevils"],
    reviewed: "2026-07-20",
    added: "2026-07-19",
    popularity: 71,
  },
  {
    slug: "beetles",
    name: "Beetles",
    scientificName: "Coleoptera, including Epilachna and flea beetles",
    category: "pest",
    kind: "Chewing insect",
    image: "chewing-pest",
    summary:
      "Hard-shelled chewing insects. Adults strip leaves while their grubs often feed on roots below ground.",
    identification: [
      "Round shot-hole damage from flea beetles, or lace-like skeletonising from leaf beetles.",
      "Hard-bodied insects that drop or jump when disturbed.",
      "Yellow egg clusters on leaf undersides in some species.",
      "Spiny or grub-like larvae feeding beside the adults.",
    ],
    symptoms: [
      "Many small round holes in young leaves",
      "Leaves reduced to a network of veins",
      "Seedlings killed outright in heavy flea beetle attacks",
      "Weak plants from root-feeding grubs",
    ],
    causes: [
      "Adults overwintering in field trash and hedgerows",
      "Continuous cropping of the same family",
      "Warm dry spells favouring flea beetle activity",
      "Bare soil making it easy for beetles to find seedlings",
    ],
    weather: ["Hot and dry", "Warm and humid"],
    weatherNote:
      "Flea beetles are most active in warm dry weather; many leaf beetles peak after the first rains.",
    plants: ["Brinjal", "Cucurbits", "Cabbage", "Mustard", "Beans", "Potato"],
    severity: "Medium",
    difficulty: "Moderate",
    seasons: ["Spring", "Summer", "Monsoon"],
    prevention: [
      "Cover young seedlings with fine netting until they toughen up",
      "Rotate crop families and clear residue",
      "Transplant strong seedlings rather than direct seeding in high-risk fields",
      "Use trap crops on field margins",
    ],
    organic: [
      "Hand-pick adults and crush egg clusters in the morning when beetles are slow",
      "Neem or spinosad sprays on young crops",
      "Sticky traps and straw mulch to make it harder for beetles to move",
    ],
    chemical: [
      "Seed treatments protect seedlings through the vulnerable stage",
      "Foliar options are used only above the local damage threshold",
      "Avoid spraying flowering crops when pollinators are active",
    ],
    practices: [
      "Check seedlings daily for the first two weeks",
      "Focus control on the seedling stage; older plants tolerate holes",
      "Keep field edges tidy over winter",
    ],
    tags: ["shot holes", "flea beetle", "skeletonised leaves", "grubs", "chewing"],
    related: ["weevils", "caterpillars", "grasshoppers", "leaf-miners"],
    reviewed: "2026-07-20",
    added: "2026-07-20",
    popularity: 62,
  },
  {
    slug: "grasshoppers",
    name: "Grasshoppers and Locusts",
    scientificName: "Acrididae family",
    category: "pest",
    kind: "Chewing insect",
    image: "chewing-pest",
    summary:
      "Strong jaws that chew leaves from the edge inward. Usually a border problem, but locust swarms can clear a whole field.",
    identification: [
      "Ragged chewing from the leaf edge, working inward.",
      "Damage worst along field margins and near grassland.",
      "Insects jump or fly away as you walk through.",
      "Egg pods buried in firm undisturbed soil.",
    ],
    symptoms: [
      "Leaves eaten back to the midrib",
      "Chewed stems and stripped seedlings",
      "Damage concentrated on the outer rows",
      "Total defoliation where a swarm lands",
    ],
    causes: [
      "Nearby uncultivated grassland where eggs are laid",
      "Dry seasons followed by fresh green growth",
      "Undisturbed field margins holding egg pods",
      "Regional swarm migrations in locust-prone areas",
    ],
    weather: ["Hot and dry", "Mild and dry"],
    weatherNote: "Hatching follows warming soil after rain; adults feed most in hot sunny weather.",
    plants: ["Maize", "Rice", "Sorghum", "Vegetables", "Pasture", "Young trees"],
    severity: "Medium",
    difficulty: "Moderate",
    seasons: ["Summer", "Autumn"],
    prevention: [
      "Cultivate field margins to destroy egg pods before hatching",
      "Keep a mown or tilled barrier strip around high-value crops",
      "Protect young trees with sleeves or netting",
      "Watch official locust bulletins in affected regions",
    ],
    organic: [
      "Metarhizium acridum biopesticide, used in official locust programmes",
      "Netting over nursery beds and small plots",
      "Encourage birds and poultry along field edges",
      "Hand-collect hoppers in the early morning while they are sluggish",
    ],
    chemical: [
      "Border-strip treatments are usually enough for normal grasshopper numbers",
      "Locust swarms are handled by government control operations, not individual farmers",
      "Blanket field spraying is rarely justified and harms beneficial insects",
    ],
    practices: [
      "Treat the hopper stage before the insects gain wings",
      "Focus effort on the field edge, where numbers are highest",
      "Report unusual hopper bands to local authorities",
    ],
    tags: ["locust", "chewed edges", "hoppers", "field margin", "swarm"],
    related: ["armyworms", "caterpillars", "beetles", "cutworms"],
    reviewed: "2026-07-21",
    added: "2026-07-20",
    popularity: 57,
  },
  {
    slug: "stem-borers",
    name: "Stem Borers",
    scientificName: "Chilo, Scirpophaga, Busseola and Sesamia species",
    category: "pest",
    kind: "Boring insect",
    image: "chewing-pest",
    summary:
      "Larvae that tunnel inside stems, cutting the plant's plumbing. In rice this shows as dead hearts and white heads.",
    identification: [
      "A small entry hole in the stem with frass around it.",
      "Central shoot dries out and pulls out easily: the dead heart.",
      "Empty white panicles standing above a green crop: the white head.",
      "Split the stem lengthwise and you will find the tunnel and larva.",
    ],
    symptoms: [
      "Dead central shoots in young plants",
      "White empty panicles at flowering",
      "Broken and lodged stems",
      "Holes with sawdust-like frass on stems and cobs",
    ],
    causes: [
      "Moths laying eggs on leaf sheaths and undersides",
      "Stubble and residue carrying larvae to the next season",
      "Staggered planting dates giving continuous host material",
      "Excess nitrogen making soft attractive stems",
    ],
    weather: ["Warm and humid", "Heavy rain"],
    weatherNote:
      "Moth flights peak in warm humid weather; several generations occur in a long growing season.",
    plants: ["Rice", "Maize", "Sugarcane", "Sorghum", "Millet"],
    severity: "High",
    difficulty: "Hard",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Plough or destroy stubble immediately after harvest",
      "Plant the whole area in a tight window so the crop passes the risky stage together",
      "Grow tolerant varieties where they exist",
      "Balance nitrogen instead of pushing heavy doses",
    ],
    organic: [
      "Release Trichogramma egg parasitoids at the recommended interval",
      "Clip leaf tips with visible egg masses before transplanting rice",
      "Push-pull intercropping with Desmodium and Napier grass in maize",
      "Light traps to monitor and reduce adult moths",
    ],
    chemical: [
      "Granular products applied into the whorl or paddy water where registered",
      "Timing to egg hatch is critical; larvae inside the stem cannot be reached",
      "Rotate modes of action and avoid routine calendar sprays",
    ],
    practices: [
      "Count dead hearts per square metre weekly",
      "Use light and pheromone traps to time control",
      "Coordinate planting dates with neighbouring farms",
    ],
    tags: ["dead heart", "white head", "rice borer", "tunnel in stem", "maize"],
    related: ["armyworms", "caterpillars", "leafhoppers", "termites"],
    reviewed: "2026-07-21",
    added: "2026-07-21",
    popularity: 69,
  },
  {
    slug: "leafhoppers",
    name: "Leafhoppers",
    scientificName: "Amrasca, Nephotettix and related genera",
    category: "pest",
    kind: "Sap-sucking insect",
    image: "sucking-pest",
    summary:
      "Small wedge-shaped insects that run sideways and hop away. Their feeding burns leaf edges and spreads serious viruses.",
    identification: [
      "Pale green or brown wedge-shaped insects on the leaf underside.",
      "They scuttle sideways when the leaf is turned.",
      "Leaf edges turn yellow then brown and curl downward.",
      "Damage is called hopper burn.",
    ],
    symptoms: [
      "Yellowing then browning of leaf margins",
      "Downward cupping and crisp leaf edges",
      "Stunted plants with reduced yield",
      "Yellow dwarf and other virus symptoms in rice",
      "Sooty mould from honeydew in heavy attacks",
    ],
    causes: [
      "Warm weather with fast generation turnover",
      "Dense nitrogen-rich crops",
      "Loss of spiders and other natural enemies from spraying",
      "Continuous host cropping across seasons",
    ],
    weather: ["Warm and humid", "Hot and dry"],
    weatherNote:
      "Numbers build in warm humid weather; hopper burn shows fastest when plants are also water-stressed.",
    plants: ["Cotton", "Okra", "Rice", "Brinjal", "Grape", "Mango", "Potato"],
    severity: "High",
    difficulty: "Moderate",
    seasons: ["Monsoon", "Summer"],
    prevention: [
      "Choose hairy-leaved tolerant varieties where available",
      "Avoid excessive nitrogen",
      "Keep spiders and other predators by avoiding blanket sprays",
      "Remove alternate weed hosts around the field",
    ],
    organic: [
      "Neem oil sprays directed at leaf undersides",
      "Yellow sticky traps for monitoring",
      "Encourage spiders and mirid bugs, which are strong natural enemies",
    ],
    chemical: [
      "Selective options such as flonicamid or dinotefuran where registered",
      "Rotate modes of action; resistance is common in rice and cotton systems",
      "Treat based on hopper counts per plant, not on a calendar",
    ],
    practices: [
      "Shake plants over a white tray to count hoppers weekly",
      "Watch for hopper burn on field edges first",
      "Keep the crop evenly watered to reduce stress symptoms",
    ],
    tags: ["hopper burn", "jassids", "yellow edges", "rice", "cotton", "sideways"],
    related: ["aphids", "whiteflies", "thrips", "mosaic-virus"],
    reviewed: "2026-07-22",
    added: "2026-07-21",
    popularity: 65,
  },
  {
    slug: "cutworms",
    name: "Cutworms",
    scientificName: "Agrotis species",
    category: "pest",
    kind: "Soil insect",
    image: "soil-pest",
    summary:
      "Night-feeding caterpillars that cut young seedlings off at ground level, then hide in the soil during the day.",
    identification: [
      "Seedlings cut clean through at soil level and left lying.",
      "Fat greasy grey-brown caterpillars that curl into a C when touched.",
      "They hide 2-5 cm deep next to the damaged plant.",
      "Damage appears overnight in patches.",
    ],
    symptoms: [
      "Young plants toppled and severed at the base",
      "Gaps appearing along the row each morning",
      "Chewed stems and leaves near the ground",
      "Wilting plants where the stem is partly cut",
    ],
    causes: [
      "Moths laying eggs in weedy or grassy fields before planting",
      "Crop planted straight after grass or a weedy fallow",
      "Moist soil with plenty of surface residue",
      "Warm nights speeding up larval feeding",
    ],
    weather: ["Warm and humid", "Cool and wet"],
    weatherNote: "Damage peaks in mild moist nights early in the season, when seedlings are small.",
    plants: ["Tomato", "Cabbage", "Maize", "Beans", "Chilli", "Most transplants"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Spring", "Monsoon"],
    prevention: [
      "Clear weeds and grass at least two weeks before planting",
      "Cultivate the soil to expose larvae to birds",
      "Delay planting slightly after ploughing a grassy field",
      "Keep a weed-free strip around the plot",
    ],
    organic: [
      "Place collars of cardboard or plastic around each transplant stem",
      "Dig around a damaged plant in the morning and remove the larva by hand",
      "Bran bait with Bacillus thuringiensis scattered at dusk",
      "Encourage birds by leaving perches around the field",
    ],
    chemical: [
      "Bait formulations applied at dusk work better than foliar sprays",
      "Soil-applied products are used where damage history is severe",
      "Treat only the affected patch, not the whole field",
    ],
    practices: [
      "Walk the rows each morning during the first two weeks after planting",
      "Replant gaps promptly to keep the stand even",
      "Record which blocks had cutworm damage for next season",
    ],
    tags: ["cut seedlings", "night feeding", "curl into c", "soil larvae", "transplant"],
    related: ["armyworms", "caterpillars", "damping-off", "termites"],
    reviewed: "2026-07-22",
    added: "2026-07-22",
    popularity: 73,
  },
  {
    slug: "snails-and-slugs",
    name: "Snails and Slugs",
    scientificName: "Gastropoda, including Deroceras and Achatina species",
    category: "pest",
    kind: "Mollusc",
    image: "soil-pest",
    summary:
      "Night feeders that rasp irregular holes in soft leaves and leave shining slime trails behind them.",
    identification: [
      "Ragged holes with smooth edges in soft leaves.",
      "Silvery dried slime trails on leaves and soil in the morning.",
      "Damage appears overnight, worst after rain.",
      "Hiding under pots, boards, mulch and dense foliage by day.",
    ],
    symptoms: [
      "Large irregular holes in leaves and seedlings",
      "Whole seedlings eaten to the ground",
      "Scarred fruit lying near the soil surface",
      "Slime trails across leaves and paths",
    ],
    causes: [
      "Wet weather and constantly damp mulch",
      "Dense ground cover and hiding places near beds",
      "Heavy irrigation late in the day",
      "Shady, poorly drained plots",
    ],
    weather: ["Cool and wet", "Heavy rain", "Waterlogged soil"],
    weatherNote: "Feeding peaks on mild damp nights; activity almost stops in hot dry weather.",
    plants: ["Lettuce", "Cabbage", "Strawberry", "Seedlings", "Ornamentals", "Beans"],
    severity: "Medium",
    difficulty: "Easy",
    seasons: ["Monsoon", "Spring", "Autumn"],
    prevention: [
      "Water in the morning so the surface dries before nightfall",
      "Remove boards, bricks and rubbish that give daytime shelter",
      "Keep mulch thin and away from young stems",
      "Improve drainage in low, damp corners",
    ],
    organic: [
      "Hand-collect at night with a torch, which is very effective in small plots",
      "Copper tape barriers around beds and pots",
      "Iron phosphate baits, which are safer around pets and wildlife",
      "Encourage ducks, frogs, birds and ground beetles",
    ],
    chemical: [
      "Metaldehyde baits are restricted or banned in many countries: check local rules",
      "Where allowed, scatter bait thinly rather than in heaps",
      "Keep all baits away from children, pets and waterways",
    ],
    practices: [
      "Check beds after each rain",
      "Protect seedlings first; older plants can take some damage",
      "Clear weeds and hiding places before planting",
    ],
    tags: ["slime trails", "night damage", "holes in lettuce", "wet weather", "bait"],
    related: ["cutworms", "caterpillars", "beetles", "damping-off"],
    reviewed: "2026-07-23",
    added: "2026-07-22",
    popularity: 59,
  },
  {
    slug: "termites",
    name: "Termites",
    scientificName: "Odontotermes, Microtermes and related genera",
    category: "pest",
    kind: "Soil insect",
    image: "soil-pest",
    summary:
      "Soil insects that hollow out roots and stems, especially in dry seasons and in fields rich in undecomposed straw.",
    identification: [
      "Soil tubes and earthen sheeting plastered on stems and trunks.",
      "Plants pull up easily because the roots are eaten away.",
      "Hollowed stems packed with soil.",
      "Patches of dead plants that widen over time.",
    ],
    symptoms: [
      "Sudden wilting and death of scattered plants",
      "Roots and stem bases eaten hollow",
      "Lodging of mature cereal plants",
      "Damaged seedlings soon after planting",
      "Bark eaten from young trees at ground level",
    ],
    causes: [
      "Dry spells that push termites onto living plants",
      "Large amounts of raw straw or residue in the soil",
      "Nearby termite mounds",
      "Poor irrigation and drought-stressed crops",
    ],
    weather: ["Hot and dry", "Mild and dry"],
    weatherNote: "Attacks peak in prolonged dry weather; good irrigation greatly reduces losses.",
    plants: ["Sugarcane", "Wheat", "Maize", "Groundnut", "Young fruit trees"],
    severity: "Medium",
    difficulty: "Hard",
    seasons: ["Summer", "Winter"],
    prevention: [
      "Compost residue properly instead of ploughing in raw straw",
      "Irrigate adequately during dry spells",
      "Destroy termite mounds near the field, including the queen",
      "Avoid injuring young tree trunks",
    ],
    organic: [
      "Flood irrigation disturbs colonies in field crops",
      "Apply well-rotted farmyard manure rather than fresh straw",
      "Metarhizium biopesticides applied to soil where available",
      "Neem cake worked into the planting hole",
    ],
    chemical: [
      "Seed treatment or planting-hole treatment where locally registered",
      "Soil applications are used for high-value orchards and sugarcane",
      "Broadcast field sprays are ineffective against underground colonies",
    ],
    practices: [
      "Inspect stems at ground level in dry weather",
      "Plant into moist soil and keep young trees watered",
      "Map affected patches and treat them at planting next season",
    ],
    tags: ["soil tubes", "hollow stems", "dry season", "sugarcane", "mound"],
    related: ["cutworms", "ants", "nematodes", "root-rot"],
    reviewed: "2026-07-23",
    added: "2026-07-23",
    popularity: 54,
  },
  {
    slug: "ants",
    name: "Ants",
    scientificName: "Formicidae family",
    category: "pest",
    kind: "Soil insect",
    image: "soil-pest",
    summary:
      "Usually not the real pest. Ants farm aphids, mealybugs and scale for honeydew and drive away the predators that would control them.",
    identification: [
      "Steady trails of ants running up stems and along branches.",
      "Aphid, mealybug or scale colonies at the end of the trail.",
      "Loose soil mounds around the plant base or in pots.",
      "Ants aggressively chasing off ladybirds and wasps.",
    ],
    symptoms: [
      "Sap-sucking pest colonies that keep coming back after treatment",
      "Sticky honeydew and sooty mould spreading through the canopy",
      "Roots disturbed by nesting in pots and seedbeds",
      "Leaf-cutter species stripping foliage in the Americas",
    ],
    causes: [
      "An existing honeydew-producing pest colony to farm",
      "Dry sheltered soil suitable for nesting",
      "Food waste and fallen sweet fruit nearby",
      "Undisturbed mulch and pot bases",
    ],
    weather: ["Hot and dry", "Mild and dry"],
    weatherNote: "Most active in warm dry weather; nests move higher when soil floods.",
    plants: ["Citrus", "Mango", "Cotton", "Potted plants", "Vegetables"],
    severity: "Low",
    difficulty: "Moderate",
    seasons: ["Summer", "Spring"],
    prevention: [
      "Treat the honeydew pest and the ants will usually leave",
      "Keep grass and weeds away from tree trunks",
      "Clear fallen fruit and food waste",
      "Do not let branches touch fences or the ground and bridge the barrier",
    ],
    organic: [
      "Sticky bands around trunks to block trails",
      "Boric acid sugar baits placed on the trail, not sprayed on plants",
      "Diatomaceous earth around pots and beds",
      "Flood or disturb nests in seedbeds",
    ],
    chemical: [
      "Bait stations work far better than contact sprays because workers carry the bait to the nest",
      "Avoid spraying whole canopies for ants: it kills beneficial insects",
      "Keep all baits away from children, animals and water",
    ],
    practices: [
      "Follow the trail to find the pest colony that is feeding them",
      "Renew sticky bands regularly; dust makes them useless",
      "Treat ants and sap-sucking pests together as one problem",
    ],
    tags: ["ant trails", "honeydew farming", "sticky band", "bait", "secondary pest"],
    related: ["aphids", "mealybugs", "scale-insects", "termites"],
    reviewed: "2026-07-24",
    added: "2026-07-23",
    popularity: 52,
  },
  {
    slug: "weevils",
    name: "Weevils",
    scientificName: "Curculionidae family",
    category: "pest",
    kind: "Chewing insect",
    image: "soil-pest",
    summary:
      "Beetles with a long snout. Adults notch leaves while the grubs bore into stems, tubers, bananas and stored grain.",
    identification: [
      "Adults with a distinct downward-curved snout.",
      "Half-moon notches chewed from leaf edges.",
      "Small round exit holes in stored grain, tubers or stems.",
      "Fine powder or frass around the hole.",
    ],
    symptoms: [
      "Notched leaf margins on legumes and ornamentals",
      "Tunnelled sweet potato tubers with a bitter taste",
      "Collapsing banana pseudostems from corm damage",
      "Hollow grain and dust in storage",
      "Wilting rice or maize seedlings from root feeding",
    ],
    causes: [
      "Infested planting material such as banana suckers or seed tubers",
      "Storing grain that was already infested in the field",
      "Warm humid stores with no hygiene between seasons",
      "Crop residue and volunteer plants harbouring adults",
    ],
    weather: ["Warm and humid", "Hot and dry"],
    weatherNote:
      "Field weevils build up in warm weather; storage weevils breed year-round in warm humid stores.",
    plants: ["Sweet potato", "Banana", "Rice", "Maize", "Stored grain", "Legumes"],
    severity: "Medium",
    difficulty: "Moderate",
    seasons: ["All year", "Summer"],
    prevention: [
      "Use clean, pared and treated planting material",
      "Hill sweet potato so cracks do not expose tubers",
      "Harvest on time; late harvest suffers the most damage",
      "Clean and dry stores completely before filling them",
    ],
    organic: [
      "Pheromone traps for sweet potato and banana weevils",
      "Split pseudostem traps to catch adult banana weevils",
      "Hermetic airtight storage bags, which kill grain weevils without chemicals",
      "Dry grain to a safe moisture level before storing",
    ],
    chemical: [
      "Registered grain protectants may be used in commercial storage",
      "Fumigation must only be done by trained, licensed operators",
      "Never use field insecticides on grain intended for eating",
    ],
    practices: [
      "Inspect stores monthly and sieve a sample of grain",
      "Rotate stock so old grain is used first",
      "Do not mix new harvest with old, possibly infested grain",
    ],
    tags: ["snout beetle", "notched leaves", "stored grain", "sweet potato", "banana"],
    related: ["beetles", "fruit-flies", "stem-borers", "caterpillars"],
    reviewed: "2026-07-24",
    added: "2026-07-24",
    popularity: 56,
  },
  {
    slug: "nematodes",
    name: "Root-Knot Nematodes",
    scientificName: "Meloidogyne species",
    category: "pest",
    kind: "Roundworm",
    image: "soil-root",
    summary:
      "Microscopic soil worms that make swollen galls on roots, so plants cannot take up water and nutrients properly.",
    identification: [
      "Round swollen galls along the roots that cannot be rubbed off.",
      "Galls are part of the root, unlike the smooth nodules of legumes.",
      "Patchy poor growth across a field, often in sandy areas.",
      "Plants wilt in the afternoon even in moist soil.",
    ],
    symptoms: [
      "Stunted, yellowing plants in patches",
      "Wilting during the hottest hours despite watering",
      "Knotted, swollen, forked roots",
      "Poor yield and small fruit",
      "Higher losses from wilt diseases that enter through nematode wounds",
    ],
    causes: [
      "Sandy soils with low organic matter",
      "Continuous cropping of susceptible vegetables",
      "Infested soil, water and transplants moved between fields",
      "Warm soil temperatures speeding up the life cycle",
    ],
    weather: ["Hot and dry", "Warm and humid"],
    weatherNote:
      "Multiply fastest in warm soils of 25-30°C; damage shows most when plants are also under water stress.",
    plants: ["Tomato", "Carrot", "Okra", "Cucumber", "Banana", "Chilli", "Pepper"],
    severity: "High",
    difficulty: "Hard",
    seasons: ["Summer", "All year"],
    prevention: [
      "Rotate with cereals, maize or marigold for at least two seasons",
      "Plant resistant tomato and pepper varieties where available",
      "Raise seedlings in clean, sterile media",
      "Do not move soil or water from an infested block to a clean one",
    ],
    organic: [
      "Add plenty of compost and manure to support nematode-eating soil life",
      "Grow and incorporate marigold as a rotation or trap crop",
      "Soil solarisation with clear plastic in the hottest weeks",
      "Biological products based on Paecilomyces or Bacillus firmus",
    ],
    chemical: [
      "Chemical nematicides are highly regulated and often restricted",
      "Rotation, resistant varieties and organic matter give better long-term results",
      "Never apply soil chemicals without professional advice",
    ],
    practices: [
      "Dig up a few poor plants and inspect the roots before blaming nutrition",
      "Map affected patches and rotate them out of susceptible crops",
      "Clean soil off tools and machinery between fields",
    ],
    tags: ["root knot", "galls", "stunted", "sandy soil", "meloidogyne", "soil test"],
    related: ["fusarium-wilt", "bacterial-wilt", "root-rot", "termites"],
    reviewed: "2026-07-25",
    added: "2026-07-24",
    popularity: 67,
  },
];
