/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutAiRouteImport } from './routes/about-ai'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as CareRouteImport } from './routes/care'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OutbreaksRouteImport } from './routes/outbreaks'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as KnowledgeIndexRouteImport } from './routes/knowledge.index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutAiRoute = AboutAiRouteImport.update({
  id: '/about-ai',
  path: '/about-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OutbreaksRoute = OutbreaksRouteImport.update({
  id: '/outbreaks',
  path: '/outbreaks',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeIndexRoute = KnowledgeIndexRouteImport.update({
  id: '/knowledge/',
  path: '/knowledge/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/knowledge/$slug',
  path: '/knowledge/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ai': typeof AboutAiRoute
  '/advisor': typeof AdvisorRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/outbreaks': typeof OutbreaksRoute
  '/weather': typeof WeatherRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ai': typeof AboutAiRoute
  '/advisor': typeof AdvisorRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/outbreaks': typeof OutbreaksRoute
  '/weather': typeof WeatherRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge': typeof KnowledgeIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/about-ai': typeof AboutAiRoute
  '/advisor': typeof AdvisorRoute
  '/care': typeof CareRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/outbreaks': typeof OutbreaksRoute
  '/weather': typeof WeatherRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
  '/knowledge/': typeof KnowledgeIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/about-ai'
    | '/advisor'
    | '/care'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/outbreaks'
    | '/weather'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/api/public/health'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/about-ai'
    | '/advisor'
    | '/care'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/outbreaks'
    | '/weather'
    | '/knowledge/$slug'
    | '/knowledge'
    | '/api/public/health'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/about-ai'
    | '/advisor'
    | '/care'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/outbreaks'
    | '/weather'
    | '/knowledge/$slug'
    | '/knowledge/'
    | '/api/public/health'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AboutAiRoute: typeof AboutAiRoute
  AdvisorRoute: typeof AdvisorRoute
  CareRoute: typeof CareRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  OutbreaksRoute: typeof OutbreaksRoute
  WeatherRoute: typeof WeatherRoute
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
  KnowledgeIndexRoute: typeof KnowledgeIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-ai': {
      id: '/about-ai'
      path: '/about-ai'
      fullPath: '/about-ai'
      preLoaderRoute: typeof AboutAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outbreaks': {
      id: '/outbreaks'
      path: '/outbreaks'
      fullPath: '/outbreaks'
      preLoaderRoute: typeof OutbreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/': {
      id: '/knowledge/'
      path: '/knowledge'
      fullPath: '/knowledge/'
      preLoaderRoute: typeof KnowledgeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/knowledge/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AboutAiRoute: AboutAiRoute,
  AdvisorRoute: AdvisorRoute,
  CareRoute: CareRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  OutbreaksRoute: OutbreaksRoute,
  WeatherRoute: WeatherRoute,
  KnowledgeSlugRoute: KnowledgeSlugRoute,
  KnowledgeIndexRoute: KnowledgeIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
